-- String definitions for different games

doom.obitStrings = {
	default = {
		default = {
			"%o died.",
			"%o met their end.",
			"%o didn't make it.",
			"%o has fallen.",
			"%o is no more."
		},

		default_player = {
			"%o was killed by %k.",
			"%k took out %o.",
			"%o was defeated by %k.",
			"%o didn't survive %k.",
			"%k ended %o."
		},

		default_player_projectile = {
			"%o died to %k's projectile.",
			"%o was hit by %k's projectile.",
			"%k's projectile finished off %o.",
			"%o couldn't dodge %k's shot.",
			"%o was taken down by %k's projectile."
		},

		default_projectile = {
			"%o died to a projectile.",
			"%o was struck by a projectile.",
			"%o couldn't avoid the projectile.",
			"%o was taken out by a stray shot.",
			"%o caught a projectile."
		},

		friendlyfire = {
			"%k mowed down a teammate.",
			"%k betrayed %o.",
			"%o was shot by a teammate.",
			"%o was eliminated by friendly fire.",
			"%k accidentally eliminated %o.",
			"%o fell victim to a teamkill.",
			"%k made a grave mistake.",
			"%o was killed by their own ally.",
			"%k turned against %o.",
			"%o was caught in friendly crossfire.",
		},
		exit = {
			"%o thought they could leave early.",
			"%o attempted an unauthorized departure.",
			"%o tried to skip out.",
			"%o sought an early exit.",
			"%o attempted to flee the battlefield.",
			"%o tried to quit while they were ahead.",
			"%o sought a premature conclusion.",
			"%o attempted an illegal escape.",
			"%o tried to leave without permission.",
			"%o sought freedom from the carnage."
		},
		fall = {
			"%o fell too far.",
			"%o discovered gravity still works.",
			"%o took the quick way down.",
			"%o forgot about terminal velocity.",
			"%o experienced rapid unplanned disassembly.",
			"%o learned about kinetic energy.",
			"%o met the ground too hard.",
			"%o tested the limits of fall damage.",
			"%o forgot their parachute.",
			"%o experienced sudden lithobraking."
		},
		crush = {
			"%o was squished.",
			"%o met the wrong side of heavy machinery.",
			"%o experienced extreme compression.",
			"%o was flattened.",
			"%o became two-dimensional.",
			"%o got compacted.",
			"%o was pancaked.",
			"%o met an immovable object.",
			"%o was turned into a stain.",
			"%o experienced structural failure."
		},
		drown = {
			"%o couldn't swim.",
			"%o forgot to come up for air.",
			"%o discovered they're not waterproof.",
			"%o took the plunge permanently.",
			"%o attempted underwater breathing.",
			"%o found Davy Jones' locker.",
			"%o learned a lesson about buoyancy.",
			"%o sank like a rock.",
			"%o took a permanent bath.",
			"%o met a watery grave."
		},
		water = {
			"%o got themselves into hot water.",
			"%o discovered the hard way that water can be dangerous.",
			"%o found themselves in over their head.",
			"%o learned to respect the power of water.",
			"%o was overwhelmed by the current.",
			"%o couldn't handle the depth.",
			"%o was swept away by the tide.",
			"%o became a victim of their own curiosity.",
			"%o took a swim in the wrong place.",
			"%o found themselves drowning in their own mistakes."
		},
		slime = {
			"%o mutated.",
			"%o experienced chemical recombination.",
			"%o dissolved in acid.",
			"%o became a science experiment.",
			"%o learned slime is bad for your health.",
			"%o was assimilated by goo.",
			"%o experienced rapid cellular decay.",
			"%o forgot their hazmat suit.",
			"%o was digested by the environment.",
			"%o became one with the ooze."
		},
		lava = {
			"%o melted.",
			"%o took a dip in the hot tub.",
			"%o became one with the magma.",
			"%o forgot lava is hot.",
			"%o experienced thermal overload.",
			"%o was reduced to their component molecules.",
			"%o attempted to swim in rock.",
			"%o discovered their melting point.",
			"%o was thermally deconstructed.",
			"%o found the floor was lava, literally."
		},
		barrel = {
			"%o went boom.",
			"%o triggered an explosive surprise.",
			"%o discovered barrels are volatile.",
			"%o learned not to stand near explosives.",
			"%o was eliminated by environmental hazards.",
			"%o found the wrong container.",
			"%o had a barrel of bad luck.",
			"%o experienced rapid disassembly.",
			"%o was turned into confetti.",
			"%o made a barrel go kaboom."
		},
		barrel_player = {
			"%o was caught in %k's explosive chain reaction.",
			"%o paid the price for %k's barrel play.",
			"%o was too close when %k set things off.",
			"%o got caught in %k's environmental hazard.",
			"%o learned barrels listen to %k.",
			"%o was blown apart thanks to %k.",
			"%o suffered from %k's explosive solution.",
			"%o was erased by %k's barrel tactics."
		},
		barrel_monster = {
			"%o was blown up by a monster-triggered barrel.",
			"%o stood too close to a demon's bad idea.",
			"%o was caught in a monster-made explosion.",
			"%o learned monsters don't respect explosives.",
			"%o was collateral damage in a demon firefight.",
			"%o was undone by a monster's stray attack.",
			"%o paid for a monster's poor aim.",
			"%o was eliminated by demonic environmental hazards.",
			"%o stood between a monster and a barrel.",
			"%o discovered barrels answer to monsters too."
		},
		barrel_self = {
			"%o set off their own explosive trap.",
			"%o learned not to play with explosives.",
			"%o became a victim of their own barrel.",
			"%o triggered their own demise.",
		},

		monster_infighting = {
			"%o was caught between two fighting monsters.",
			"%o was collateral damage in a demon dispute.",
			"%o stood in the wrong place during monster infighting.",
			"%o learned monsters don't care about bystanders.",
		},

		rocket = {
			"%o should have stood back.",
			"%o got too close to the rocket.",
			"%o was blown up by a rocket.",
			"%o met a rocket up close.",
		},
		rocket_splash_self = {
			"%o didn't respect their own rocket's personal space.",
			"%o learned rocket safety the hard way.",
			"%o was caught in their own blast.",
			"%o forgot rockets explode.",
			"%o gave themselves a taste of their own medicine.",
			"%o failed the rocket jump.",
			"%o got too cozy with their own explosion.",
			"%o was their own worst enemy.",
			"%o discovered rockets don't discriminate.",
			"%o violated the cardinal rule of rocket launchers."
		},
		rocket_splash = {
			"%o should have stood back.",
			"%o was caught in rocket splash damage.",
			"%o was too close to the explosion.",
			"%o didn't respect the rocket's blast radius.",
			"%o stood in the wrong spot.",
			"%o was in the blast zone.",
			"%o didn't move fast enough.",
			"%o caught the edge of an explosion.",
			"%o failed to respect explosive force.",
			"%o was collateral damage.",
			"%o stood where things go boom.",
			"%o forgot about splash damage.",
			"%o was too close for comfort.",
			"%o learned about blast radius the hard way."
		},
		self = {
			"%o took the easy way out.",
			"%o decided they'd had enough.",
			"%o committed suicide.",
			"%o ended their own misery.",
			"%o gave up the fight.",
			"%o checked out early.",
			"%o took matters into their own hands.",
			"%o said goodbye to this mortal coil.",
			"%o met their own maker.",
			"%o decided to stop existing."
		},
		voodoo = "%o experienced the power of voodoo.",
		telefrag_player = {
			"%o was telefragged by %k.",
			"%o was obliterated by %k's teleportation.",
			"%k teleported right through %o.",
			"%o got in the way of %k's teleporter.",
		},
		telefrag = {
			"%o was telefragged.",
			"%o got telefragged.",
			"%o was destroyed by a teleporter.",
			"%o experienced teleporter overlap.",
		},

		revenant_melee = "%o was punched by a revenant.",
		imp_melee = "%o was slashed by an imp.",
		cacodemon_melee = "%o got too close to a cacodemon.",
		demon_melee = "%o was bit by a demon.",
		spectre_melee = "%o was eaten by a spectre.",
		baron_melee = "%o was ripped open by a Baron of Hell.",
		hellknight_melee = "%o was gutted by a Hell Knight.",

		zombieman = "%o was killed by a zombieman.",
		shotgunner = "%o was shot by a shotgunner.",
		archvile = "%o was incinerated by an archvile.",
		revenant = "%o couldn't evade a revenant's fireball.",
		mancubus = "%o was squashed by a mancubus.",
		chaingunner = "%o was perforated by a chaingunner.",
		lostsoul = "%o was spooked by a lost soul.",
		imp = "%o was burned by an imp.",
		cacodemon = "%o was smitten by a cacodemon.",
		baron = "%o was bruised by a Baron of Hell.",
		hellknight = "%o was splayed by a Hell Knight.",
		spidermastermind = "%o stood in awe of the spider demon.",
		arachnotron = "%o let an arachnotron get them.",
		cyberdemon = "%o was splattered by a cyberdemon.",
		ssguard = "%o met a Nazi.",
		painelemental = {
			"%o achieved the impossible.",
			"%o somehow died to a Pain Elemental.",
			"%o lost to something that shouldn't be lethal.",
			"%o found a new way to lose."
		},
		commanderkeen = {
			"%o was beaten down by a child.",
			"%o lost a fight they were never meant to have.",
			"%o was defeated by Commander Keen.",
			"%o should not have lost this."
		},

		revenant_melee_wrongtarget = "%o caught a revenant's punch meant for someone else.",
		imp_melee_wrongtarget = "%o was slashed by an imp swinging at the wrong target.",
		cacodemon_melee_wrongtarget = "%o wandered into a cacodemon's bad decision.",
		demon_melee_wrongtarget = "%o was bitten by a demon not paying attention.",
		spectre_melee_wrongtarget = "%o was eaten by a spectre that lost track of its prey.",
		baron_melee_wrongtarget = "%o took a Baron of Hell's rage personally.",
		hellknight_melee_wrongtarget = "%o intercepted a Hell Knight's swing.",

		zombieman_wrongtarget = "%o was caught in a zombieman's stray shot.",
		shotgunner_wrongtarget = "%o walked into a shotgun blast not meant for them.",
		archvile_wrongtarget = "%o was incinerated by an archvile with poor aim.",
		revenant_wrongtarget = "%o was hit by a revenant firing at the wrong enemy.",
		mancubus_wrongtarget = "%o stood where a mancubus was shooting.",
		chaingunner_wrongtarget = "%o was perforated by indiscriminate gunfire.",
		lostsoul_wrongtarget = "%o drifted into a lost soul's bad pathing.",
		imp_wrongtarget = "%o was burned by an imp missing its mark.",
		cacodemon_wrongtarget = "%o was blasted by a cacodemon not targeting them.",
		baron_wrongtarget = "%o was bruised by a Baron lashing out blindly.",
		hellknight_wrongtarget = "%o was splayed by collateral damage.",
		spidermastermind_wrongtarget = "%o stood between the spider demon and its real target.",
		arachnotron_wrongtarget = "%o crossed an arachnotron's firing line.",
		cyberdemon_wrongtarget = "%o was obliterated by a cyberdemon aiming elsewhere.",
		ssguard_wrongtarget = "%o was shot by a Nazi who picked the wrong target.",
		painelemental_wrongtarget = {
			"%o somehow died to a Pain Elemental's mistake.",
			"%o was collateral damage in the least lethal fight imaginable.",
			"%o caught something that wasn't meant for them.",
			"%o became a statistical anomaly."
		},
		commanderkeen_wrongtarget = {
			"%o lost to something that wasn't even trying.",
			"%o was defeated by an impossible mistake.",
			"%o became an error state.",
			"%o should not exist in this obituary."
		},

		revenant_melee_brassknuckles = {
			"%o got into a boxing fight with a revenant and lost.",
			"%o tried to settle it with a revenant the gentleman's way.",
			"%o chose fisticuffs with a creature whose fists break bones as a hobby.",
			"%o thought 'stand and deliver' applied to the undead.",
			"%o proposed a pugilistic solution to an arcane problem.",
			"%o's brass knuckles were proven decorative against a true professional.",
			"%o was dispatched by a revenant's one-two.",
			"%o tried to outbox a revenant.",
			"%o tried to fight a revenant with dignity.",
			"%o learned why you don't fistfight the undead.",
			"%o found out revenants have a mean right hook."
		},

		shotgunner_shotgun = {
			"%o tried to out-shotgun a shotgunner.",
			"%o challenged a shotgunner to a close-range debate.",
			"%o brought a shotgun to a shotgunner fight.",
		},

		zombieman_pistol = {
			"%o tried to win a pistol duel against a zombieman.",
			"%o trusted the starting weapon too much.",
			"%o lost a low-budget gunfight.",
		},

		arachnotron_plasma = {
			"%o attempted to out-plasma an arachnotron.",
			"%o challenged a spider to a plasma exchange.",
			"%o learned why arachnotrons own the color blue.",
		},

		-- "To defeat the cyberdemon, shoot it until it dies" - Doom Bible
		-- What's worse is the fact that even the map recommends using the Rocket Launcher against it
		-- When it has a hardcoded check to NOT take splash damage
		cyberdemon_rocketlauncher = {
			"%o shot the cyberdemon until they died.",
			"%o misunderstood who was meant to die first.",
			"%o learned the cyberdemon shoots back.",
			"%o found out rockets aren't one-sided.",
			"%o discovered the cyberdemon's counterattack.",
		},

		cyberdemon_pistol = {
			"%o tried to out-pistol a cyberdemon.",
			"%o challenged a cyberdemon to a pistol duel.",
			"%o learned pistols are ineffective against cyberdemons.",
		},

		cyberdemon_brassknuckles = {
			"%o tried to fistfight a cyberdemon.",
			"%o challenged a cyberdemon to a bare-knuckle brawl.",
			"%o learned brass knuckles are useless against cyberdemons.",
		},

		spidermastermind_chaingun = {
			"%o tried to out-chaingun a spider mastermind.",
			"%o challenged a spider mastermind to a bullet contest.",
			"%o learned chainguns are the spider mastermind's specialty.",
		},

		chaingunner_chaingun = "%o tried to beat a chaingunner in their own turf.",

		brassknuckles = {
			"%o chewed on %k's fist.",
			"%o was punched to death by %k's brass knuckles.",
			"%o underestimated %k's knuckle duster skills.",
			"%o got a knuckle sandwich from %k.",
			"%o learned not to mess with %k's brass knuckles.",
			"%o was knocked out cold by %k's fists of fury.",
			"%o found out %k packs a punch with brass knuckles.",
			"%o was on the receiving end of %k's brass knuckle justice.",
			"%o got their lights knocked out by %k.",
			"%o discovered %k's brass knuckles are more than just for show.",
			"%o was flattened by %k's brass knuckle barrage."
		},

		-- While the %k is under the effects of the Berserk Pack
		brassknuckles_berserk = {
			"%o was pulverized by berserk %k's brass knuckles.",
			"%o got demolished by %k's berserk fists.",
			"%o was wrecked by %k's berserk knuckle duster.",
		},

		-- This is also able to be berserk-boosted
		chainsaw_berserk = {
			"%o was shredded by %k's berserk chainsaw.",
			"%o got torn apart by %k's berserk chainsaw.",
			"%o was cut to pieces by %k's berserk chainsaw.",
			"%o was sawed in half by %k's berserk chainsaw.",
		},

		-- When the victim has the Brass Knuckles while the assailant uses the chainsaw
		brassknuckles_chainsaw = {
			"%o tried to block %k's chainsaw with brass knuckles.",
			"%o learned brass knuckles don't stop chainsaws.",
			"%o found out the hard way that brass knuckles can't defend against a chainsaw.",
			"%o discovered brass knuckles are useless against %k's chainsaw.",
			"%o brought brass knuckles to a chainsaw fight.",
			"%o tried to box with a chainsaw-wielding %k.",
			"%o brought knuckles to a chainsaw fight.",
		},

		-- When the opposite of the above happens :kappa:
		-- Unlikely to happen unless the victim has REALLY low health
		chainsaw_brassknuckles = {
			"%o brought a chainsaw to a brass knuckle fight and lost.",
			"%o somehow lost a chainsaw duel to %k's fists.",
			"%o learned the hard way that chainsaws aren't everything.",
			"%o was outboxed despite wielding a chainsaw.",
			"%o underestimated %k's brass knuckles while revving a chainsaw.",
			"%o found out that even a chainsaw can't save you from a good punch.",
		},

		brassknuckles_pistol = {
			"%o tried to prove a point to %k with brass knuckles and got shot instead.",
			"%o brought knuckles to a gunfight with %k.",
			"%o thought fists were enough against %k's pistol.",
			"%o got pewed by %k after aiming for a punch.",
			"%o forgot bullets beat brass knuckles, per %k.",
			"%o found out %k's pistol has better reach than their fists.",
		},

		brassknuckles_shotgun = {
			"%o swung brass knuckles and caught %k's scattershot.",
			"%o was outgunned by %k's boomstick.",
			"%o punched the wrong barrel and paid the price to %k.",
			"%o learned why you don't box with a shotgun from %k.",
			"%o ended up on the receiving end of %k's point-blank justice.",
			"%o tried to parry pellets with knuckles — it didn't work against %k.",
		},

		brassknuckles_chaingun = {
			"%o tried a one-two punch on %k's chaingun and lost.",
			"%o found %k's lead answer to their brass knuckles.",
			"%o got a rapid reminder from %k that range matters.",
			"%o learned the hard way that knuckles don't stop a gatling.",
			"%o was peppered into silence by %k's chaingun.",
			"%o swung for glory and was shredded by %k's fire.",
		},

		brassknuckles_rocketlauncher = {
			"%o tried to sock %k and rode their rocket instead.",
			"%o brought brass knuckles to a guided vacation courtesy of %k.",
			"%o met %k's rocket with a fist and lost the trip.",
			"%o forgot about splash damage while aiming for %k.",
			"%o attempted to box the blast and became %k's crater.",
			"%o learned that rockets > knuckles, thanks to %k.",
		},

		brassknuckles_plasmarifle = {
			"%o tried to up close %k's plasma beam with knuckles.",
			"%o was fried by %k's plasma for bringing fists.",
			"%o thought knuckles could withstand plasma — they couldn't against %k.",
			"%o got a scorching lesson from %k's rifle.",
			"%o swung for a hit and got melted by %k.",
			"%o found out %k's plasma doesn't care about brass.",
		},

		brassknuckles_bfg9000 = {
			"%o brought a knuckle fight to a BFG and lost spectacularly to %k.",
			"%o tried to box %k's BFG and became a statistic.",
			"%o discovered brass knuckles don't stop BFG splinters from %k.",
			"%o was obliterated by %k after a hopeful punch.",
			"%o aimed for a punch and hit the wrong end of %k's BFG.",
			"%o went to trade blows with %k's BFG and got obliterated.",
		},

		chainsaw_pistol = {
			"%o revved their chainsaw at %k but got a bullet instead.",
			"%o thought shredding was the answer — %k had other plans.",
			"%o tried to close the gap on %k's pistol and failed.",
			"%o got put down by %k's steady hand while revving.",
			"%o discovered a toe-to-trigger mismatch with %k.",
			"%o met %k's bullet before their chainsaw could bite.",
		},

		chainsaw_shotgun = {
			"%o swung a chainsaw into %k's scatter and lost.",
			"%o learned up close that shotguns are point-blank arguments against chainsaws.",
			"%o revved too close to %k's boomstick.",
			"%o tried to chew past %k and got blasted instead.",
			"%o was stopped cold by %k's shotgun blast.",
			"%o found their chainsaw unsatisfying against %k's pellets.",
		},

		chainsaw_chaingun = {
			"%o thought their chainsaw could handle the hail from %k's chaingun.",
			"%o got peppered off their feet by %k's rapid fire.",
			"%o revved but couldn't rev past %k's rhythm.",
			"%o was shredded by bullets while swinging a saw at %k.",
			"%o discovered %k's chaingun outpaced their blade.",
			"%o tried to bite into a wall of lead from %k and failed.",
		},

		chainsaw_rocketlauncher = {
			"%o aimed the chainsaw and found a rocket in the way from %k.",
			"%o tried to cut through %k's explosives and became airborne.",
			"%o brought a blade to a blast fight with %k.",
			"%o revved for close combat and rode %k's rocket instead.",
			"%o learned rockets don't play nice with chainsaws from %k.",
			"%o met %k's splash damage up close and personal.",
		},

		chainsaw_plasmarifle = {
			"%o tried to slice %k's plasma and got seared.",
			"%o revved into a beam of regret from %k's rifle.",
			"%o discovered plasma dulls chainsaw edges very quickly against %k.",
			"%o got melted while their saw whined uselessly at %k.",
			"%o swung for metal and found out %k had energy.",
			"%o couldn't chew through %k's plasma fire.",
		},

		chainsaw_bfg9000 = {
			"%o aimed the saw at %k and got BFG'd instead.",
			"%o tried to win a close-quarters chainsaw duel with %k's BFG and lost.",
			"%o was turned into confetti by %k's BFG blast.",
			"%o revved the wrong way and triggered %k's BFG judgement.",
			"%o found out chainsaws are insignificant next to %k's BFG.",
			"%o attempted a slice and met a cosmic pain courtesy of %k.",
		},

		pistol_brassknuckles = {
			"%o thought shooting would save them from %k's fists, but %k closed the gap.",
			"%o ran out of bullets and into %k's knuckle lesson.",
			"%o discovered close combat beats a pistol when %k sets the pace.",
			"%o tried to pull trigger and got a fist to the face from %k.",
			"%o was outmaneuvered by %k and their brass knuckles.",
			"%o fired a shot and got a punch from %k for their trouble.",
		},

		shotgun_brassknuckles = {
			"%o had pellets left but not enough to stop %k's oncoming fists.",
			"%o swung the boomstick and walked into %k's knuckle shuffle.",
			"%o found %k's fists had better aim up close.",
			"%o fired point-blank and then tasted %k's brass.",
			"%o tried to blast and got blasted in return by %k's fists.",
			"%o underestimated %k's boxing with knuckles.",
		},

		chaingun_brassknuckles = {
			"%o emptied a clip and still got a knuckle to the jaw from %k.",
			"%o thought bullets were forever until %k closed in with brass.",
			"%o was overwhelmed by %k's closing speed and knuckles.",
			"%o gatling fire couldn't stop %k's one-two knuckle punch.",
			"%o fired until empty, then felt %k's fist.",
			"%o found out rapid fire doesn't stop a determined fist from %k.",
		},

		rocketlauncher_brassknuckles = {
			"%o tried to rocket away and ran into %k's fist instead.",
			"%o launched hope and hit %k's knuckle hammer.",
			"%o detonated themselves little-to-no help against %k's close blow.",
			"%o relied on rockets but couldn't outrun %k's punch.",
			"%o found one rocket doesn't beat a well-timed knuckle from %k.",
			"%o misjudged the distance and ate %k's brass knuckles.",
		},

		plasmarifle_brassknuckles = {
			"%o thought energy rounds would scare %k, who closed in with brass.",
			"%o got a plasma zap then a knuckle tap from %k.",
			"%o fired beams but couldn't keep %k at bay.",
			"%o discovered energy weapons need backup when %k gets personal.",
			"%o was whittled down by plasma and finished with a punch from %k.",
			"%o tried to snipe and got snuck up on by %k's fists.",
		},

		bfg9000_brassknuckles = {
			"%o fired the BFG and still got up close and personal with %k's knuckles.",
			"%o unleashed doom but %k proved hands are faster up close.",
			"%o was BFG'd into a mess and then pounded by %k.",
			"%o thought the BFG guaranteed victory until %k proved otherwise.",
			"%o got a fatal assist from their own blast and a finishing punch by %k.",
			"%o learned the BFG doesn't teach manners against %k's fists.",
		},

		chainsaw = "%o was carved up by %k's chainsaw.",
		pistol = "%o was tickled by %k's pea shooter.",
		shotgun = "%o chewed on %k's boomstick.",
		supershotgun = "%o was splattered by %k's super shotgun.",
		chaingun = "%o got a lead transfusion from %k's chaingun.",
		rocketlauncher = "%o rode %k's rocket.",
		rocketlauncher_splash = "%o almost dodged %k's rocket.",
		plasmarifle = "%o was melted by %k's plasma gun.",
		bfg9000 = "%o was splintered by %k's BFG.",
		bfg9000_tracer = "%o was lazzed by %k.",

		chainsaw_friendlyfire = {
			"%k mistook %o for demon fodder.",
			"%o got too close to %k's chainsaw.",
			"%k revved up and forgot about %o.",
			"%o was carved up by a teammate.",
			"%k's chainsaw didn't care about team colors.",
			"%o learned the hard way to stay behind %k.",
			"%k turned %o into friendly giblets.",
			"%o was on the wrong end of %k's chainsaw.",
		},

		chaingun_friendlyfire = {
			"%k hosed down %o with friendly fire.",
			"%o stepped into %k's bullet stream.",
			"%k held the trigger and forgot about %o.",
			"%o was perforated by a teammate's chaingun.",
			"%k's chaingun chewed through friend and foe alike.",
			"%o caught every round %k fired.",
			"%k's suppressing fire suppressed %o permanently.",
		},

		rocketlauncher_friendlyfire = {
			"%k team-rocketed %o.",
			"%o was caught in %k's 'friendly' rocket blast.",
			"%k cleared the room, including their teammate %o.",
		},

		bfg9000_friendlyfire = {
			"%k team-BFG'd %o.",
			"%o was collateral damage in %k's green beam of friendship.",
			"%k's BFG didn't discriminate between friend and foe.",
		},

		brassknuckles_self = {
			"%o fought themself and lost.",
			"%o got into a fistfight with a mirror.",
			"%o answered 'Why are you hitting yourself?'",
			"%o couldn't control their own hands.",
			"%o was their own worst sparring partner.",
			"%o punched themself in the face.",
			"%o took 'self-defense' too literally.",
			"%o beat themself up.",
			"%o hurt themselves in their own confusion.",
			"%o discovered fisting themself is a bad idea.",
			"%o lost to their own shadowboxing.",
			"%o's reflexes betrayed them.",
			"%o got tangled up with their own fists."
		},

		chainsaw_self = {
			"%o discovered why you don't test a chainsaw on yourself.",
			"%o sawed off more than they could chew.",
			"%o got up close and personal with their own chainsaw.",
			"%o performed self-surgery without anesthesia.",
			"%o learned chainsaws don't discriminate.",
			"%o gave themself a haircut they'll never forget.",
			"%o got caught in their own woodworking.",
			"%o didn't respect the business end of their chainsaw.",
			"%o tried to juggle a running chainsaw.",
			"%o became one with the sawdust."
		},

		pistol_self = {
			"%o played Russian roulette with an automatic.",
			"%o had an unfortunate pistol malfunction.",
			"%o tried to holster their pistol while it was firing.",
			"%o shot themself while cleaning their weapon.",
			"%o got a bullet from an unexpected angle.",
			"%o lost a game of pistol twirling.",
			"%o discovered the trigger works both ways.",
			"%o was their own worst accidental discharge.",
			"%o tried to catch a bullet.",
			"%o gave themself a lead injection."
		},

		shotgun_self = {
			"%o tried to smell the shotgun barrel.",
			"%o learned shotguns have a kick.",
			"%o got too close to their own blast pattern.",
			"%o checked if the safety was on.",
			"%o gave themself a buckshot makeover.",
			"%o tested shotgun recoil without bracing.",
			"%o played 'is it loaded?' and lost.",
			"%o was on the wrong end of their own boomstick.",
			"%o didn't respect their own spread."
		},

		supershotgun_self = {
			"%o didn't respect the double barrel.",
			"%o caught both barrels with their own face.",
			"%o tried to fire the super shotgun one-handed.",
			"%o discovered why it's called 'super'.",
			"%o got double the trouble from their own weapon.",
			"%o was their own worst overkill.",
			"%o didn't brace for the super kick.",
			"%o was obliterated by their own firepower.",
			"%o learned that two barrels are worse than one."
		},

		chaingun_self = {
			"%o got caught in their own bullet hose.",
			"%o forgot which way the chaingun spins.",
			"%o tried to stop the barrels with their hand.",
			"%o was shredded by their own leadstorm.",
			"%o discovered why it's called a 'chain' gun.",
			"%o got too close to their own firing arc.",
			"%o was perforated by their own weapon.",
			"%o didn't control the recoil.",
			"%o tried to fire the chaingun while spinning.",
			"%o was their own bullet blender."
		},

		rocketlauncher_self = {
			"%o ate their own rocket.",
			"%o learned not to look down the rocket tube.",
			"%o fired a rocket at point-blank range.",
			"%o tried to catch their own rocket.",
			"%o was their own rocket's first victim.",
			"%o didn't clear the backblast area.",
			"%o discovered rockets are not for close quarters.",
			"%o fired a rocket with their back to a wall.",
			"%o tried to use the rocket launcher as a melee weapon.",
			"%o became one with their own propulsion system."
		},

		plasmarifle_self = {
			"%o was melted by their own plasma.",
			"%o tried to touch the pretty plasma ball.",
			"%o learned plasma is hot from both ends.",
			"%o caught their own superheated goo.",
			"%o was their own microwave dinner.",
			"%o didn't respect the plasma splash.",
			"%o tried to juggle plasma cells.",
			"%o was dissolved by their own energy weapon.",
			"%o got a taste of their own hot plasma.",
			"%o learned plasma doesn't discriminate."
		},

		bfg9000_self = {
			"%o was erased by their own BFG.",
			"%o didn't stand clear of the BFG discharge.",
			"%o tried to fire the BFG in a phone booth.",
			"%o was atomized by their own creation.",
			"%o learned why it's called 'Big F***ing Gun'.",
			"%o caught the full force of their own BFG.",
			"%o was their own worst overkill.",
			"%o didn't respect the BFG's backblast.",
			"%o tried to fire the BFG while moving backwards.",
			"%o was consumed by their own green death."
		},

		bfg9000_tracer_self = {
			"%o was vaporized by their own BFG tracer.",
			"%o got hit by their own stray BFG energy.",
			"%o was caught in their own BFG's web.",
			"%o learned tracers don't care who fired them.",
			"%o was their own collateral damage.",
			"%o dodged into their own BFG stream.",
			"%o was lasered by their own weapon.",
			"%o didn't clear the BFG's firing lane.",
			"%o was eliminated by their own supporting fire.",
			"%o found out BFG tracers are equal opportunity killers."
		},

		pinv_revenant = {
			"%o couldn't shake a revenant missile.",
			"%o forgot invisibility doesn't fool homing rockets.",
			"%o vanished, but the missile didn't care.",
		},
		pinv_mancubus = {
			"%o walked into a mancubus spread.",
			"%o trusted invisibility against a mancubus.",
			"%o discovered blast patterns the hard way.",
			"%o couldn't see the angle on the mancubus.",
			"%o faded straight into twin fireballs.",
			"%o learned why invisibility hates mancubi.",
		},
		pinv_projectile = {
			"%o zigged when the projectile zagged.",
			"%o was hit by a shot meant for someone else.",
			"%o dodged directly into danger.",
			"%o confused the enemy - but not the projectile.",
			"%o got unlucky while invisible.",
		},
		pinv_default = {
			"%o trusted partial invisibility.",
			"%o thought they were harder to hit.",
			"%o relied on fuzz a little too much.",
			"%o vanished, then died anyway.",
			"%o faded from view, then from existence.",
			"%o learned invisibility isn't invincibility.",
			"%o couldn't see the danger coming.",
			"%o misjudged their invisibility.",
			"%o faded out and got blown apart.",
		},
		invuln = {
			"%o was killed despite being invulnerable.",
			"%o discovered invulnerability has limits.",
			"%o's godhood was revoked.",
			"%o learned immortality is a lie.",
			"%o died while nothing could hurt them.",
			"%o was invincible. It didn't help.",
			"%o's invulnerability failed catastrophically.",
			"%o defied death. Death disagreed.",
			"%o died anyway.",
			"%o was beyond saving.",
			"%o met an unstoppable force.",
		},
		invuln_telefrag = {
			"%o was telefragged despite being invulnerable.",
			"%o's invulnerability couldn't stop a telefrag.",
			"%k telefragged %o through god mode.",
			"%o found out telefrags ignore godhood.",
			"%o was erased from existence by %k.",
			"%o occupied the wrong space at the wrong time.",
		},

		invuln_overkill = {
			"%o was hit with more damage than godhood allows.",
			"%o was destroyed on a fundamental level.",
			"%o suffered existential damage.",
			"%o was annihilated beyond invulnerability.",
			"%o was hit by something that doesn't care.",
		},

		-- This can literally only happen if the player runs the kill command :kappa:
		-- This means we can have some fun with the messages here
		invuln_self = {
			"%o couldn't bear the burden of godhood.",
			"%o found a loophole in immortality.",
			"%o's invulnerability had a self-destruct clause.",
			"%o decided that even gods must die.",
			"%o chose to revoke their own divinity.",
			"%o's will to live faltered, despite invincibility.",
			"%o discovered that invulnerability can't stop oneself.",
			"%o turned god mode against themself.",
			"%o proved that even gods can commit suicide.",
			"%o found the one thing that could kill them: themself.",
		},

		invuln_telefrag_player = {
			"%k telefragged %o despite their invulnerability.",
			"%o's godhood was no match for %k's teleportation.",
			"%k found a way to kill a god: telefrag %o.",
			"%o's invulnerability failed against %k's spatial displacement.",
			"%k erased %o from reality, ignoring their god mode.",
			"%o occupied space that %k decided to claim.",
		},
	},
	srb2 = {
		default = "%o died.",
		default_player = "%o was killed by %k.",
		exit = {
			"%o tried to leave.",
			"%o attempted to exit.",
			"%o wanted out.",
			"%o tried to escape.",
			"%o sought the exit."
		},
		fall = {
			"%o fell.",
			"%o fell too far.",
			"%o was destroyed by falling.",
			"%o hit the ground too hard.",
			"%o took fall damage."
		},
		crush = {
			"%o was crushed.",
			"%o was squished.",
			"%o was flattened.",
			"%o was destroyed by crushing.",
			"%o met a heavy object."
		},
		water = {
			"%o drowned.",
			"%o sank.",
			"%o fell in water.",
			"%o was destroyed by water.",
			"%o couldn't swim."
		},
		slime = {
			"%o melted.",
			"%o dissolved.",
			"%o was destroyed by slime.",
			"%o fell in slime.",
			"%o was melted by slime."
		},
		lava = {
			"%o burned.",
			"%o melted.",
			"%o was burned by lava.",
			"%o fell in lava.",
			"%o was destroyed by lava."
		},
		barrel = {
			"%o blew up.",
			"%o exploded.",
			"%o was caught in an explosion.",
			"%o triggered a barrel.",
			"%o was destroyed by a barrel."
		},

		friendlyfire = {
			"%o was killed by a teammate.",
			"%k killed %o.",
			"%o was caught in friendly fire.",
			"%k made a mistake.",
		},

		rocket = {
			"%o was blown up.",
			"%o stood too close.",
			"%o caught a rocket.",
		},
		rocket_splash_self = {
			"%o blew themselves up.",
			"%o was caught in their own blast.",
			"%o didn't move fast enough.",
			"%o got too close to their own rocket.",
			"%o learned about splash damage."
		},
		rocket_splash = {
			"%o was caught in the blast.",
			"%o didn't move fast enough.",
			"%o was in the wrong place.",
			"%o was caught in the explosion.",
			"%o didn't move in time.",
			"%o stood too close.",
			"%o was hit by the blast."
		},

		telefrag_player = {
			"%o was telefragged by %k.",
			"%o got in %k's way.",
		},
		telefrag = "%o was telefragged.",

		revenant_melee = "%o was punched by a revenant.",
		imp_melee = "%o was slashed.",
		demon_melee = "%o was bitten.",
		spectre_melee = "%o was eaten.",
		baron_melee = "%o was ripped apart.",
		hellknight_melee = "%o was gutted.",

		zombieman = "%o was killed by a crawla.",
		shotgunner = "%o was shot by a super crawla.",
		chaingunner = "%o was perforated.",
		imp = "%o was burned.",
		lostsoul = "%o was hit by a rockbot.",
		cacodemon = "%o was blasted by a cacodemon.",
		baron = "%o was smashed by a Baron of Hell.",
		hellknight = "%o was smashed by a Hell Knight.",
		arachnotron = "%o was gunned down.",
		revenant = "%o couldn't dodge the missile.",
		mancubus = "%o was flattened.",
		archvile = "%o was incinerated.",
		spidermastermind = "%o was shredded.",
		cyberdemon = "%o didn't survive.",
		ssguard = "%o met a Nazi.",

		brassknuckles = "%o was punched.",
		chainsaw = "%o was sawed in half.",
		pistol = "%o was shot.",
		shotgun = "%o was blasted.",
		supershotgun = "%o was blown apart.",
		chaingun = "%o was riddled with bullets.",
		rocketlauncher = "%o was blown up by %k.",
		rocketlauncher_splash = "%o was caught in the explosion.",
		plasmarifle = "%o was vaporized.",
		bfg9000 = "%o was destroyed.",
		bfg9000_tracer = "%o was hit by the BFG.",

		pinv = {
			"%o was hit anyway.",
			"%o wasn't invisible enough.",
		},
		pinv_projectile = "%o dodged wrong.",

		invuln = {
			"%o died anyway.",
			"%o wasn't as invulnerable as they thought.",
		},
		invulntelefrag = "%o was telefragged.",
		invulnoverkill = "%o was destroyed.",

		default_player_projectile = {
			"%o was hit by %k's projectile.",
			"%o couldn't dodge %k's attack.",
			"%o was nailed by %k's shot.",
			"%o didn't see %k's projectile coming.",
			"%o got tagged by %k."
		},
		default_projectile = {
			"%o was struck by a projectile.",
			"%o got hit by something flying.",
			"%o ate a random shot.",
			"%o stepped into the line of fire.",
			"%o caught a stray projectile."
		},
		drown = {
			"%o sank into the depths.",
			"%o drowned in the water.",
			"%o learned not to swim.",
			"%o went under.",
			"%o couldn't hold their breath."
		},
		barrel_monster = {
			"%o was caught in a monster's explosion.",
			"%o was blown up by something.",
			"%o paid for a monster's blast.",
			"%o stood too close to the chaos.",
			"%o was caught in collateral damage."
		},
		monster_infighting = {
			"%o was caught in the crossfire.",
			"%o was in the wrong place at the wrong time.",
			"%o paid the price for monster chaos.",
			"%o got caught between enemies.",
			"%o was collateral damage."
		},
		pinv_revenant = {
			"%o couldn't dodge while invisible.",
			"%o was hit anyway.",
		},
		pinv_mancubus = {
			"%o couldn't avoid the blast.",
			"%o got hit while faded.",
		},
		voodoo = "%o was voodoo cursed.",
		painelemental = "%o somehow lost to that.",
		commanderkeen = "%o lost to an unexpected foe.",
		chainsaw_friendlyfire = {
			"%k sliced %o.",
			"%o got in %k's way with a chainsaw.",
		},
		chaingun_friendlyfire = {
			"%k sprayed %o with bullets.",
			"%o walked into %k's fire.",
		},
		rocketlauncher_friendlyfire = {
			"%k rocketed %o.",
			"%o was caught in %k's blast.",
		},
		bfg9000_friendlyfire = {
			"%k blasted %o.",
			"%o was destroyed by %k.",
		},
	},
	chexquest = {
		default = "%o was zorched out of this dimension.",
		default_player = "%o was zorched by %k.",
		friendlyfire = {
			"%k accidentally zorched a teammate.",
			"%o was caught in friendly zorchfire.",
			"%k slimed one of their own.",
			"%o was mistakenly de-flemified.",
			"%k made a cheesy mistake.",
			"%o was removed by team zorch.",
		},
		exit = {
			"%o attempted premature evacuation.",
			"%o tried to escape the Flemoid dimension.",
			"%o sought unauthorized departure.",
			"%o attempted dimensional exit.",
			"%o tried to leave the slime zone."
		},
		fall = {
			"%o slipped out of existence.",
			"%o experienced gravitational failure.",
			"%o fell through dimensions.",
			"%o met an abrupt stop.",
			"%o learned about gravity."
		},
		crush = {
			"%o was compressed into goo.",
			"%o experienced extreme Flemoid pressure.",
			"%o was flattened by machinery.",
			"%o was compacted into Flemoid paste.",
			"%o met a compressive end."
		},
		water = {
			"%o dissolved in the slime.",
			"%o was broken down by Flemoid liquids.",
			"%o experienced aqueous decomposition.",
			"%o met a liquid end.",
			"%o was dissolved by Flemoid fluids."
		},
		slime = {
			"%o was absorbed by slime.",
			"%o became part of the Flemoid ecosystem.",
			"%o experienced complete assimilation.",
			"%o was digested by the environment.",
			"%o merged with the Flemoid substrate."
		},
		lava = {
			"%o melted into goo.",
			"%o was reduced to Flemoid residue.",
			"%o experienced thermal decomposition.",
			"%o became one with the magma.",
			"%o was liquefied by extreme heat."
		},
		barrel = {
			"%o triggered a slime reaction.",
			"%o caused a Flemoid chemical explosion.",
			"%o was caught in a slime detonation.",
			"%o discovered volatile Flemoid materials.",
			"%o experienced rapid de-flemification."
		},
		rocket = {
			"%o stood too close to the zorch blast.",
			"%o tested the blast radius.",
			"%o learned about splash damage.",
		},
		rocket_splash_self = {
			"%o zorched themselves.",
			"%o caught their own zorch wave.",
			"%o learned about self-zorching.",
			"%o was de-flemified by their own hand.",
			"%o experienced personal zorch feedback."
		},
		self = {
			"%o zorched themselves.",
			"%o self-de-flemified.",
			"%o removed themselves from existence.",
			"%o committed zorch-suicide.",
			"%o was their own worst zorch-enemy.",
			"%o performed a self-zorching.",
			"%o's hand slipped on the zorcher.",
			"%o experienced accidental self-removal.",
		},
		rocket_splash = {
			"%o was caught in a zorch wave.",
			"%o didn't dodge the blast.",
			"%o was slimed by the shockwave.",
			"%o stood in the wrong slime zone.",
			"%o was caught in secondary zorch.",
			"%o experienced residual Flemoid energy.",
			"%o was slimed by the aftermath.",
			"%o didn't clear the blast area."
		},

		voodoo = "%o experienced unexplained zorch physics.",

		telefrag_player = {
			"%o was displaced by %k.",
			"%o occupied the same space as %k.",
			"%k popped into %o.",
			"%o was removed via teleport mishap.",
		},
		telefrag = {
			"%o was removed by spatial overlap.",
			"%o couldn't share that space.",
			"%o was displaced violently.",
		},

		revenant_melee = "%o was walloped by a Flemoid.",
		imp_melee = "%o was slimed by an armored bipedicus.",
		demon_melee = "%o was chomped by a Flemoid.",
		spectre_melee = "%o was slimed by an unseen Flemoid.",
		baron_melee = "%o was defeated by the Flembrane.",

		zombieman = "%o was slimed by a flemoid.",
		shotgunner = "%o was blasted by a bipedicus.",
		mancubus = "%o walked into a slime barrage.",
		chaingunner = "%o was peppered with slime.",
		lostsoul = "%o was bonked by a floating Flemoid.",
		imp = "%o was hit by an armored bipedicus.",
		baron = "%o was defeated by the Flembrane.",
		spidermastermind = "%o was overwhelmed by Flemoid engineering.",
		arachnotron = "%o stood in the wrong firing lane.",
		cyberdemon = "%o was utterly zorched.",
		painelemental = "%o experienced excessive Flemoid physics.",
		ssguard = "%o encountered a very confused enemy.",

		brassknuckles = "%o ran into %k's bootspoon.",
		chainsaw = "%o was aggressively de-flemified by %k.",
		pistol = "%o was lightly zorched by %k.",
		shotgun = "%o was heavily zorched by %k.",
		supershotgun = "%o was super-zorched by %k.",
		chaingun = "%o was rapidly de-flemified by %k.",
		rocketlauncher = "%o rode %k's zorch blast.",
		rocketlauncher_splash = "%o almost escaped the blast.",
		plasmarifle = "%o was continuously zorched by %k.",
		bfg9000 = "%o was overwhelmingly zorched by %k.",
		bfg9000_tracer = "%o was caught in residual zorch energy.",

		pinv_mancubus = {
			"%o learned slime can still track.",
			"%o faded, but the projectile didn't.",
		},
		pinv_projectile = {
			"%o dodged into danger.",
			"%o was hit while fuzzed.",
		},
		pinv_default = {
			"%o relied on partial invisibility.",
			"%o faded out, then got zorched.",
			"%o learned fuzz isn't safety.",
		},

		invuln = {
			"%o was removed despite being protected.",
			"%o discovered invincibility has limits.",
			"%o's protection failed unexpectedly.",
		},
		invulntelefrag = {
			"%o was displaced through invulnerability.",
			"%o learned teleportation ignores shields.",
		},
		invulnoverkill = {
			"%o exceeded safe zorch limits.",
			"%o was removed on a molecular level.",
		},

		default_player_projectile = {
			"%o was hit by %k's zorch.",
			"%o couldn't dodge %k's shot.",
			"%o was pelted by %k's projectile.",
			"%o didn't see %k's zorch coming.",
			"%o got tagged by %k's attack."
		},
		default_projectile = {
			"%o was struck by a zorch.",
			"%o got hit by something flying.",
			"%o ate a random shot.",
			"%o stepped into the line of zorch fire.",
			"%o caught a stray zorch."
		},
		drown = {
			"%o sank into the Flemoid ooze.",
			"%o drowned in the slime.",
			"%o learned not to swim in goo.",
			"%o went under.",
			"%o couldn't hold their breath in slime."
		},
		barrel_monster = {
			"%o was caught in a Flemoid's explosion.",
			"%o was blown up by something.",
			"%o paid for a Flemoid's blast.",
			"%o stood too close to the chaos.",
			"%o was caught in collateral zorch."
		},
		monster_infighting = {
			"%o was caught in the crossfire.",
			"%o was in the wrong place at the wrong time.",
			"%o paid the price for Flemoid chaos.",
			"%o got caught between enemies.",
			"%o was collateral damage."
		},
		pinv_revenant = {
			"%o couldn't dodge while invisible.",
			"%o was hit anyway.",
		},
		cacodemon = "%o was blasted by a Flemoid.",
		archvile = "%o was incinerated by hostile Flemoid energy.",
		commanderkeen = "%o lost to an unexpected encounter.",
		brassknuckles_self = {
			"%o punched themselves.",
			"%o beat themselves up.",
		},
		chainsaw_self = {
			"%o couldn't handle their own chainsaw.",
			"%o slipped with the chainsaw.",
		},
		pistol_self = {
			"%o shot themselves.",
			"%o had a firearm accident.",
		},
		shotgun_self = {
			"%o shot themselves with the shotgun.",
			"%o ate buckshot.",
		},
		supershotgun_self = {
			"%o got both barrels.",
			"%o couldn't handle the recoil.",
		},
		chaingun_self = {
			"%o got caught in their own fire.",
			"%o forgot where the chaingun pointed.",
		},
		rocketlauncher_self = {
			"%o launched themselves.",
			"%o ate their own rocket.",
		},
		plasmarifle_self = {
			"%o was melted by their own plasma.",
			"%o forgot plasma is hot.",
		},
		bfg9000_self = {
			"%o was overwhelmed by their own zorch.",
			"%o couldn't handle the backlash.",
		},
		bfg9000_tracer_self = {
			"%o was hit by their own zorch beam.",
			"%o got zapped by their own weapon.",
		},
		chainsaw_friendlyfire = {
			"%k sliced %o.",
			"%o got in %k's way.",
		},
		chaingun_friendlyfire = {
			"%k sprayed %o with fire.",
			"%o walked into %k's fire.",
		},
		rocketlauncher_friendlyfire = {
			"%k zorched %o.",
			"%o was caught in %k's blast.",
		},
		bfg9000_friendlyfire = {
			"%k blasted %o.",
			"%o was destroyed by %k.",
		},
	},
}

-- Loads the strings for the specified game type
-- Effectively the same as adding the damn strings in WADLoad like before (it simply sucked more)
function doom.loadStrings(gameType)
	if gameType == "srb2" then
		doom.strings = {
			D_DEVSTR = "Development mode ON.\n",
			D_CDROM = "CD-ROM Version: default.cfg from c:\\doomdata\n",
			PRESSKEY = "press a key.",
			PRESSYN = "press y or n.",
			LOADNET = "only the server can do a load net game!\n\npress a key.",
			QLOADNET = "you can't quickload during a netgame!\n\npress a key.",
			QSAVESPOT = "you haven't picked a quicksave slot yet!\n\npress a key.",
			SAVEDEAD = "you can't save if you aren't playing!\n\npress a key.",
			QSPROMPT = "quicksave over your game named\n\n'%s'?\n\npress y or n.",
			QLPROMPT = "do you want to quickload the game named\n\n'%s'?\n\npress y or n.",
			NEWGAME = "you can't start a new game\nwhile in a network game.\n\n",
			NIGHTMARE = "are you sure? this skill level\nisn't even remotely fair.\n\npress y or n.",
			SWSTRING = "this is the shareware version of doom.\n\nyou need to order the entire trilogy.\n\npress a key.",
			MSGOFF = "Messages OFF",
			MSGON = "Messages ON",
			NETEND = "you can't end a netgame!\n\npress a key.",
			ENDGAME = "are you sure you want to end the game?\n\npress y or n.",
			DOSY = "%s\n\n(press y to quit to dos.)",
			DETAILHI = "High detail",
			DETAILLO = "Low detail",
			GAMMALVL0 = "Gamma correction OFF",
			GAMMALVL1 = "Gamma correction level 1",
			GAMMALVL2 = "Gamma correction level 2",
			GAMMALVL3 = "Gamma correction level 3",
			GAMMALVL4 = "Gamma correction level 4",
			EMPTYSTRING = "empty slot",
			GOTARMOR = "Picked up the armor.",
			GOTMEGA = "Picked up the MegaArmor!",
			GOTHTHBONUS = "Picked up a health bonus.",
			GOTARMBONUS = "Picked up an armor bonus.",
			GOTSTIM = "Picked up a stimpack.",
			GOTMEDINEED = "Picked up a medikit that you REALLY need!",
			GOTMEDIKIT = "Picked up a medikit.",
			GOTSUPER = "You found a chaos emerald!",
			GOTBLUECARD = "Picked up a blue keycard.",
			GOTYELWCARD = "Picked up a yellow keycard.",
			GOTREDCARD = "Picked up a red keycard.",
			GOTBLUESKUL = "Picked up a blue skull key.",
			GOTYELWSKUL = "Picked up a yellow skull key.",
			GOTREDSKULL = "Picked up a red skull key.",
			GOTINVUL = "Invincibility!",
			GOTBERSERK = "Berserk!",
			GOTINVIS = "Partial Invisibility",
			GOTSUIT = "Radiation Shielding Suit",
			GOTMAP = "Computer Area Map",
			GOTVISOR = "Light Amplification Visor",
			GOTMSPHERE = "MegaSphere!",
			GOTCLIP = "Picked up a clip.",
			GOTCLIPBOX = "Picked up a box of bullets.",
			GOTROCKET = "Picked up a rocket.",
			GOTROCKBOX = "Picked up a box of rockets.",
			GOTCELL = "Picked up an energy cell.",
			GOTCELLBOX = "Picked up an energy cell pack.",
			GOTSHELLS = "Picked up 4 shotgun shells.",
			GOTSHELLBOX = "Picked up a box of shotgun shells.",
			GOTBACKPACK = "Picked up a backpack full of ammo!",
			GOTBFG9000 = "You got the BFG9000!  Oh, yes.",
			GOTCHAINGUN = "You got the chaingun!",
			GOTCHAINSAW = "A chainsaw!  Find some meat!",
			GOTLAUNCHER = "You got the rocket launcher!",
			GOTPLASMA = "You got the plasma gun!",
			GOTSHOTGUN = "You got the shotgun!",
			GOTSHOTGUN2 = "You got the super shotgun!",
			PD_BLUEO = "You need a blue key to activate this object",
			PD_REDO = "You need a red key to activate this object",
			PD_YELLOWO = "You need a yellow key to activate this object",
			PD_BLUEK = "You need a blue key to open this door",
			PD_REDK = "You need a red key to open this door",
			PD_YELLOWK = "You need a yellow key to open this door",
			GGSAVED = "game saved.",
			HUSTR_MSGU = "[Message unsent]",
			HUSTR_E1M1 = "E1M1: Hangar",
			HUSTR_E1M2 = "E1M2: Nuclear Plant",
			HUSTR_E1M3 = "E1M3: Toxin Refinery",
			HUSTR_E1M4 = "E1M4: Command Control",
			HUSTR_E1M5 = "E1M5: Phobos Lab",
			HUSTR_E1M6 = "E1M6: Central Processing",
			HUSTR_E1M7 = "E1M7: Computer Station",
			HUSTR_E1M8 = "E1M8: Phobos Anomaly",
			HUSTR_E1M9 = "E1M9: Military Base",
			HUSTR_E2M1 = "E2M1: Deimos Anomaly",
			HUSTR_E2M2 = "E2M2: Containment Area",
			HUSTR_E2M3 = "E2M3: Refinery",
			HUSTR_E2M4 = "E2M4: Deimos Lab",
			HUSTR_E2M5 = "E2M5: Command Center",
			HUSTR_E2M6 = "E2M6: Halls of the Damned",
			HUSTR_E2M7 = "E2M7: Spawning Vats",
			HUSTR_E2M8 = "E2M8: Tower of Babel",
			HUSTR_E2M9 = "E2M9: Fortress of Mystery",
			HUSTR_E3M1 = "E3M1: Hell Keep",
			HUSTR_E3M2 = "E3M2: Slough of Despair",
			HUSTR_E3M3 = "E3M3: Pandemonium",
			HUSTR_E3M4 = "E3M4: House of Pain",
			HUSTR_E3M5 = "E3M5: Unholy Cathedral",
			HUSTR_E3M6 = "E3M6: Mt. Erebus",
			HUSTR_E3M7 = "E3M7: Limbo",
			HUSTR_E3M8 = "E3M8: Dis",
			HUSTR_E3M9 = "E3M9: Warrens",
			HUSTR_E4M1 = "E4M1: Hell Beneath",
			HUSTR_E4M2 = "E4M2: Perfect Hatred",
			HUSTR_E4M3 = "E4M3: Sever The Wicked",
			HUSTR_E4M4 = "E4M4: Unruly Evil",
			HUSTR_E4M5 = "E4M5: They Will Repent",
			HUSTR_E4M6 = "E4M6: Against Thee Wickedly",
			HUSTR_E4M7 = "E4M7: And Hell Followed",
			HUSTR_E4M8 = "E4M8: Unto The Cruel",
			HUSTR_E4M9 = "E4M9: Fear",
			HUSTR_1 = "Greenflower Zone Act 1",
			HUSTR_2 = "Greenflower Zone Act 2",
			HUSTR_3 = "Greenflower Zone Act 3",
			HUSTR_4 = "Techno Hill Zone Act 1",
			HUSTR_5 = "Techno Hill Zone Act 2",
			HUSTR_6 = "Techno Hill Zone Act 3",
			HUSTR_7 = "Deep Sea Zone Act 1",
			HUSTR_8 = "Deep Sea Zone Act 2",
			HUSTR_9 = "Deep Sea Zone Act 3",
			HUSTR_10 = "Mine Maze Zone Act 1",
			HUSTR_11 = "Mine Maze Zone Act 2",
			HUSTR_12 = "Mine Maze Zone Act 3",
			HUSTR_13 = "Rocky Mountain Zone Act 1",
			HUSTR_14 = "Rocky Mountain Zone Act 2",
			HUSTR_15 = "Rocky Mountain Zone Act 3",
			HUSTR_16 = "Red Volcano Zone Act 1",
			HUSTR_17 = "Red Volcano Zone Act 2",
			HUSTR_18 = "Red Volcano Zone Act 3",
			HUSTR_19 = "Dark City Zone Act 1",
			HUSTR_20 = "Dark City Zone Act 2",
			HUSTR_21 = "Dark City Zone Act 3",
			HUSTR_22 = "Doomship Zone Act 1",
			HUSTR_23 = "Doomship Zone Act 2",
			HUSTR_24 = "Doomship Zone Act 3",
			HUSTR_25 = "Robotnirock Zone Act 1",
			HUSTR_26 = "Robotnirock Zone Act 2",
			HUSTR_27 = "Robotnirock Zone Act 3",
			HUSTR_28 = "The Final Fight Zone!",
			HUSTR_29 = "Wood Zone",
			HUSTR_30 = "Dust Hill Zone",
			HUSTR_31 = "Speed Highway at Dawn",
			HUSTR_32 = "Hidden Palace Zone",
			PHUSTR_1 = "level 1: congo",
			PHUSTR_2 = "level 2: well of souls",
			PHUSTR_3 = "level 3: aztec",
			PHUSTR_4 = "level 4: caged",
			PHUSTR_5 = "level 5: ghost town",
			PHUSTR_6 = "level 6: baron's lair",
			PHUSTR_7 = "level 7: caughtyard",
			PHUSTR_8 = "level 8: realm",
			PHUSTR_9 = "level 9: abattoire",
			PHUSTR_10 = "level 10: onslaught",
			PHUSTR_11 = "level 11: hunted",
			PHUSTR_12 = "level 12: speed",
			PHUSTR_13 = "level 13: the crypt",
			PHUSTR_14 = "level 14: genesis",
			PHUSTR_15 = "level 15: the twilight",
			PHUSTR_16 = "level 16: the omen",
			PHUSTR_17 = "level 17: compound",
			PHUSTR_18 = "level 18: neurosphere",
			PHUSTR_19 = "level 19: nme",
			PHUSTR_20 = "level 20: the death domain",
			PHUSTR_21 = "level 21: slayer",
			PHUSTR_22 = "level 22: impossible mission",
			PHUSTR_23 = "level 23: tombstone",
			PHUSTR_24 = "level 24: the final frontier",
			PHUSTR_25 = "level 25: the temple of darkness",
			PHUSTR_26 = "level 26: bunker",
			PHUSTR_27 = "level 27: anti-christ",
			PHUSTR_28 = "level 28: the sewers",
			PHUSTR_29 = "level 29: odyssey of noises",
			PHUSTR_30 = "level 30: the gateway of hell",
			PHUSTR_31 = "level 31: cyberden",
			PHUSTR_32 = "level 32: go 2 it",
			THUSTR_1 = "level 1: system control",
			THUSTR_2 = "level 2: human bbq",
			THUSTR_3 = "level 3: power control",
			THUSTR_4 = "level 4: wormhole",
			THUSTR_5 = "level 5: hanger",
			THUSTR_6 = "level 6: open season",
			THUSTR_7 = "level 7: prison",
			THUSTR_8 = "level 8: metal",
			THUSTR_9 = "level 9: stronghold",
			THUSTR_10 = "level 10: redemption",
			THUSTR_11 = "level 11: storage facility",
			THUSTR_12 = "level 12: crater",
			THUSTR_13 = "level 13: nukage processing",
			THUSTR_14 = "level 14: steel works",
			THUSTR_15 = "level 15: dead zone",
			THUSTR_16 = "level 16: deepest reaches",
			THUSTR_17 = "level 17: processing area",
			THUSTR_18 = "level 18: mill",
			THUSTR_19 = "level 19: shipping/respawning",
			THUSTR_20 = "level 20: central processing",
			THUSTR_21 = "level 21: administration center",
			THUSTR_22 = "level 22: habitat",
			THUSTR_23 = "level 23: lunar mining project",
			THUSTR_24 = "level 24: quarry",
			THUSTR_25 = "level 25: baron's den",
			THUSTR_26 = "level 26: ballistyx",
			THUSTR_27 = "level 27: mount pain",
			THUSTR_28 = "level 28: heck",
			THUSTR_29 = "level 29: river styx",
			THUSTR_30 = "level 30: last call",
			THUSTR_31 = "level 31: pharaoh",
			THUSTR_32 = "level 32: caribbean",
			HUSTR_CHATMACRO1 = "I'm ready to kick ro-butt!",
			HUSTR_CHATMACRO2 = "I'm OK.",
			HUSTR_CHATMACRO3 = "I'm not looking too good!",
			HUSTR_CHATMACRO4 = "Help!",
			HUSTR_CHATMACRO5 = "You stink!",
			HUSTR_CHATMACRO6 = "Next time I'll win!",
			HUSTR_CHATMACRO7 = "Come here!",
			HUSTR_CHATMACRO8 = "I'll take care of it.",
			HUSTR_CHATMACRO9 = "Yes",
			HUSTR_CHATMACRO0 = "No",
			HUSTR_TALKTOSELF1 = "You mumble to yourself",
			HUSTR_TALKTOSELF2 = "Who's there?",
			HUSTR_TALKTOSELF3 = "You scare yourself",
			HUSTR_TALKTOSELF4 = "You start to rave",
			HUSTR_TALKTOSELF5 = "You've lost it...",
			HUSTR_MESSAGESENT = "[Message Sent]",
			AMSTR_FOLLOWON = "Follow Mode ON",
			AMSTR_FOLLOWOFF = "Follow Mode OFF",
			AMSTR_GRIDON = "Grid ON",
			AMSTR_GRIDOFF = "Grid OFF",
			AMSTR_MARKEDSPOT = "Marked Spot",
			AMSTR_MARKSCLEARED = "All Marks Cleared",
			STSTR_MUS = "Music Change",
			STSTR_NOMUS = "IMPOSSIBLE SELECTION, you stupid-head!",
			STSTR_DQDON = "Degreelessness Mode On",
			STSTR_DQDOFF = "Degreelessness Mode Off",
			STSTR_KFAADDED = "Gun Cheat Added",
			STSTR_FAADDED = "Ammo (no keys) Added",
			STSTR_NCON = "No Clipping Mode ON",
			STSTR_NCOFF = "No Clipping Mode OFF",
			STSTR_BEHOLD = "inVuln, Str, Inviso, Rad, Allmap, or Lite-amp",
			STSTR_BEHOLDX = "Power-up Toggled",
			STSTR_CHOPPERS = "... doesn't suck - GM",
			STSTR_CLEV = "Changing Level...",
			E1TEXT = "Once you beat the big badasses and\nclean out the moon base you're supposed\nto win, aren't you? Aren't you? Where's\nyour fat reward and ticket home? What\nthe hell is this? It's not supposed to\nend this way!\n\nIt stinks like rotten meat, but looks\nlike the lost Deimos base.  Looks like\nyou're stuck on The Shores of Hell.\nThe only way out is through.\n\nTo continue the DOOM experience, play\nThe Shores of Hell and its amazing\nsequel, Inferno!\n",
			E2TEXT = "You've done it! The hideous cyber-\ndemon lord that ruled the lost Deimos\nmoon base has been slain and you\nare triumphant! But ... where are\nyou? You clamber to the edge of the\nmoon and look down to see the awful\ntruth.\n\nDeimos floats above Hell itself!\nYou've never heard of anyone escaping\nfrom Hell, but you'll make the bastards\nsorry they ever heard of you! Quickly,\nyou rappel down to  the surface of\nHell.\n\nNow, it's on to the final chapter of\nDOOM! -- Inferno.",
			E3TEXT = "The loathsome spiderdemon that\nmasterminded the invasion of the moon\nbases and caused so much death has had\nits ass kicked for all time.\n\nA hidden doorway opens and you enter.\nYou've proven too tough for Hell to\ncontain, and now Hell at last plays\nfair -- for you emerge from the door\nto see the green fields of Earth!\nHome at last.\n\nYou wonder what's been happening on\nEarth while you were battling evil\nunleashed. It's good that no Hell-\nspawn could have come through that\ndoor with you ...",
			E4TEXT = "the spider mastermind must have sent forth\nits legions of hellspawn before your\nfinal confrontation with that terrible\nbeast from hell.  but you stepped forward\nand brought forth eternal damnation and\nsuffering upon the horde as a true hero\nwould in the face of something so evil.\n\nbesides, someone was gonna pay for what\nhappened to daisy, your pet rabbit.\n\nbut now, you see spread before you more\npotential pain and gibbitude as a nation\nof demons run amok among our cities.\n\nnext stop, hell on earth!",
			C1TEXT = "YOU HAVE ENTERED DEEPLY INTO THE INFESTED\nSTARPORT. BUT SOMETHING IS WRONG. THE\nMONSTERS HAVE BROUGHT THEIR OWN REALITY\nWITH THEM, AND THE STARPORT'S TECHNOLOGY\nIS BEING SUBVERTED BY THEIR PRESENCE.\n\nAHEAD, YOU SEE AN OUTPOST OF HELL, A\nFORTIFIED ZONE. IF YOU CAN GET PAST IT,\nYOU CAN PENETRATE INTO THE HAUNTED HEART\nOF THE STARBASE AND FIND THE CONTROLLING\nSWITCH WHICH HOLDS EARTH'S POPULATION\nHOSTAGE.",
			C2TEXT = "YOU HAVE WON! YOUR VICTORY HAS ENABLED\nHUMANKIND TO EVACUATE EARTH AND ESCAPE\nTHE NIGHTMARE.  NOW YOU ARE THE ONLY\nHUMAN LEFT ON THE FACE OF THE PLANET.\nCANNIBAL MUTATIONS, CARNIVOROUS ALIENS,\nAND EVIL SPIRITS ARE YOUR ONLY NEIGHBORS.\nYOU SIT BACK AND WAIT FOR DEATH, CONTENT\nTHAT YOU HAVE SAVED YOUR SPECIES.\n\nBUT THEN, EARTH CONTROL BEAMS DOWN A\nMESSAGE FROM SPACE: \nSENSORS HAVE LOCATED\nTHE SOURCE OF THE ALIEN INVASION. IF YOU\nGO THERE, YOU MAY BE ABLE TO BLOCK THEIR\nENTRY.  THE ALIEN BASE IS IN THE HEART OF\nYOUR OWN HOME CITY, NOT FAR FROM THE\nSTARPORT.\n SLOWLY AND PAINFULLY YOU GET\nUP AND RETURN TO THE FRAY.",
			C3TEXT = "YOU ARE AT THE CORRUPT HEART OF THE CITY,\nSURROUNDED BY THE CORPSES OF YOUR ENEMIES.\nYOU SEE NO WAY TO DESTROY THE CREATURES'\nENTRYWAY ON THIS SIDE, SO YOU CLENCH YOUR\nTEETH AND PLUNGE THROUGH IT.\n\nTHERE MUST BE A WAY TO CLOSE IT ON THE\nOTHER SIDE. WHAT DO YOU CARE IF YOU'VE\nGOT TO GO THROUGH HELL TO GET TO IT?",
			C4TEXT = "THE HORRENDOUS VISAGE OF THE BIGGEST\nDEMON YOU'VE EVER SEEN CRUMBLES BEFORE\nYOU, AFTER YOU PUMP YOUR ROCKETS INTO\nHIS EXPOSED BRAIN. THE MONSTER SHRIVELS\nUP AND DIES, ITS THRASHING LIMBS\nDEVASTATING UNTOLD MILES OF HELL'S\nSURFACE.\n\nYOU'VE DONE IT. THE INVASION IS OVER.\nEARTH IS SAVED. HELL IS A WRECK. YOU\nWONDER WHERE BAD FOLKS WILL GO WHEN THEY\nDIE, NOW. WIPING THE SWEAT FROM YOUR\nFOREHEAD YOU BEGIN THE LONG TREK BACK\nHOME. REBUILDING EARTH OUGHT TO BE A\nLOT MORE FUN THAN RUINING IT WAS.\n",
			C5TEXT = "CONGRATULATIONS, YOU'VE FOUND THE SECRET\nLEVEL! LOOKS LIKE IT'S BEEN BUILT BY\nHUMANS, RATHER THAN DEMONS. YOU WONDER\nWHO THE INMATES OF THIS CORNER OF HELL\nWILL BE.",
			C6TEXT = "CONGRATULATIONS, YOU'VE FOUND THE\nSUPER SECRET LEVEL!  YOU'D BETTER\nBLAZE THROUGH THIS ONE!\n",
			T1TEXT = "You've fought your way out of the infested\nexperimental labs.   It seems that UAC has\nonce again gulped it down.  With their\nhigh turnover, it must be hard for poor\nold UAC to buy corporate health insurance\nnowadays..\n\nAhead lies the military complex, now\nswarming with diseased horrors hot to get\ntheir teeth into you. With luck, the\ncomplex still has some warlike ordnance\nlaying around.",
			T2TEXT = "You hear the grinding of heavy machinery\nahead.  You sure hope they're not stamping\nout new hellspawn, but you're ready to\nream out a whole herd if you have to.\nThey might be planning a blood feast, but\nyou feel about as mean as two thousand\nmaniacs packed into one mad killer.\n\nYou don't plan to go down easy.",
			T3TEXT = "The vista opening ahead looks real damn\nfamiliar. Smells familiar, too -- like\nfried excrement. You didn't like this\nplace before, and you sure as hell ain't\nplanning to like it now. The more you\nbrood on it, the madder you get.\nHefting your gun, an evil grin trickles\nonto your face. Time to take some names.",
			T4TEXT = "Suddenly, all is silent, from one horizon\nto the other. The agonizing echo of Hell\nfades away, the nightmare sky turns to\nblue, the heaps of monster corpses start \nto evaporate along with the evil stench \nthat filled the air. Jeeze, maybe you've\ndone it. Have you really won?\n\nSomething rumbles in the distance.\nA blue light begins to glow inside the\nruined skull of the demon-spitter.",
			T5TEXT = "What now? Looks totally different. Kind\nof like King Tut's condo. Well,\nwhatever's here can't be any worse\nthan usual. Can it?  Or maybe it's best\nto let sleeping gods lie..",
			T6TEXT = "Time for a vacation. You've burst the\nbowels of hell and by golly you're ready\nfor a break. You mutter to yourself,\nMaybe someone else can kick Hell's ass\nnext time around. Ahead lies a quiet town,\nwith peaceful flowing water, quaint\nbuildings, and presumably no Hellspawn.\n\nAs you step off the transport, you hear\nthe stomp of a cyberdemon's iron shoe.",
			CC_ZOMBIE = "CRAWLA",
			CC_SHOTGUN = "SUPER CRAWLA",
			CC_HEAVY = "MINI B-EGGMAN",
			CC_IMP = "MINVS",
			CC_DEMON = "DRILLAKILLA",
			CC_LOST = "ROCKBOT",
			CC_CACO = "CACODEMON",
			CC_HELL = "HELL KNIGHT",
			CC_BARON = "BARON OF HELL",
			CC_ARACH = "ARACHNOTRON",
			CC_PAIN = "DETON",
			CC_REVEN = "REVENANT",
			CC_MANCU = "MANCUBUS",
			CC_ARCH = "ARCH-VILE",
			CC_SPIDER = "THE SPIDER MASTERMIND",
			CC_CYBER = "THE CYBERDEMON",
			CC_HERO = "OUR HERO",
			QUITMSG = "Eggman's tied explosives\nto your girlfriend, and\nwill activate them if\nyou press the 'Y' key!\nPress 'N' to save her!",
			QUITMSG1 = "What would Tails say if\nhe saw you quitting the game?",
			QUITMSG2 = "Hey!\nWhere do ya think you're goin'?",
			QUITMSG3 = "Forget your studies!\nPlay some more!",
			QUITMSG4 = "You're trying to say you\nlike Sonic Adventure better than\nthis, right?",
			QUITMSG5 = "don't leave yet -- there's a\nsuper emerald around that corner!",
			QUITMSG6 = "You'd rather work than play?",
			QUITMSG7 = "go ahead and leave. see if i care...\n*sniffle*",
			QUIT2MSG = "If you leave now,\nEggman will take over the world!",
			QUIT2MSG1 = "Don't quit!\nThere are animals\nto save!",
			QUIT2MSG2 = "Aw c'mon, just bop\na few more robots!",
			QUIT2MSG3 = "Just because you can't\nget that Chaos Emerald...",
			QUIT2MSG4 = "If you leave, i'll use\nmy spin attack on you!",
			QUIT2MSG5 = "Don't go!\nYou might find the hidden\nlevels!",
			QUIT2MSG6 = "Hit the 'N' key sonic!\nThe 'N' key!",
			FLOOR4_8 = "FLOOR4_8",
			SFLR6_1 = "SFLR6_1",
			MFLR8_4 = "MFLR8_4",
			MFLR8_3 = "MFLR8_3",
			SLIME16 = "SLIME16",
			RROCK14 = "RROCK14",
			RROCK07 = "RROCK07",
			RROCK17 = "RROCK17",
			RROCK13 = "RROCK13",
			RROCK19 = "RROCK19",
			CREDIT = "CREDIT",
			HELP2 = "HELP2",
			VICTORY2 = "VICTORY2",
			ENDPIC = "ENDPIC",
			MODIFIED = "===========================================================================\n					   Sonic Robo Blast II!\n					   by Sonic Team Junior\n				http://ssrg.emulationzone.org/stjr/\n	  This is a modified version. Go to our site for the original.\n===========================================================================\n",
			SHAREWARE = "===========================================================================\n								Shareware!\n===========================================================================\n",
			COMERCIAL = "===========================================================================\n				   We hope you enjoy this game as\n					 much as we did making it!\n===========================================================================\n",
			AUSTIN = "Austin Virtual Gaming: Levels will end after 20 minutes\n",
			M_LOAD = "M_LoadDefaults: Load system defaults.\n",
			Z_INIT = "Z_Init: Init zone memory allocation daemon. \n",
			W_INIT = "W_Init: Init WADfiles.\n",
			M_INIT = "M_Init: Init miscellaneous info.\n",
			R_INIT = "R_Init: Init DOOM refresh daemon - ",
			P_INIT = "\nP_Init: Init Playloop state.\n",
			I_INIT = "I_Init: Setting up machine state.\n",
			D_CHECKNET = "D_CheckNetGame: Checking network game status.\n",
			S_SETSOUND = "S_Init: Setting up sound.\n",
			HU_INIT = "HU_Init: Setting up heads up display.\n",
			ST_INIT = "ST_Init: Init status bar.\n",
			STATREG = "External statistics registered.\n",
			DOOM2WAD = "doom2.wad",
			DOOMUWAD = "doomu.wad",
			DOOMWAD = "doom.wad",
			DOOM1WAD = "doom1.wad",
			CDROM_DIR = "c:\\doomdata",
			CDROM_DEF = "c:/doomdata/default.cfg",
			DOOM2TITLE = "Sonic Robo Blast 2: v1.00",
			DOOMUTITLE = "The Ultimate DOOM Startup",
			DOOMTITLE = "DOOM Registered Startup",
			DOOM1TITLE = "DOOM Shareware Startup",
		}
	elseif gameType == "doom" then
		doom.strings = {
			SWSTRING	  = "this is the shareware version of doom.\n\nyou need to order the entire trilogy.\n\npress a key.",

			-- DOOM1
			QUITMSG	   = "are you sure you want to\nquit this great game?",
			QUITMSG1	  = "please don't leave, there's more\ndemons to toast!",
			QUITMSG2	  = "let's beat it -- this is turning\ninto a bloodbath!",
			QUITMSG3	  = "i wouldn't leave if i were you.\ndos is much worse.",
			QUITMSG4	  = "you're trying to say you like dos\nbetter than me, right?",
			QUITMSG5	  = "don't leave yet -- there's a\ndemon around that corner!",
			QUITMSG6	  = "ya know, next time you come in here\ni'm gonna toast ya.",
			QUITMSG7	  = "go ahead and leave. see if i care.",

			-- QuitDOOM II messages
			QUITMSG8	  = "you want to quit?\nthen, thou hast lost an eighth!",
			QUITMSG9	  = "don't go now, there's a \ndimensional shambler waiting\nat the dos prompt!",
			QUITMSG10	 = "get outta here and go back\nto your boring programs.",
			QUITMSG11	 = "if i were your boss, i'd \n deathmatch ya in a minute!",
			QUITMSG12	 = "look, bud. you leave now\nand you forfeit your body count!",
			QUITMSG13	 = "just leave. when you come\nback, i'll be waiting with a bat.",
			QUITMSG14	 = "you're lucky i don't smack\nyou for thinking about leaving.",

			-- P_inter.C
			GOTARMOR	  = "Picked up the armor.",
			GOTMEGA	   = "Picked up the MegaArmor!",
			GOTHTHBONUS   = "Picked up a health bonus.",
			GOTARMBONUS   = "Picked up an armor bonus.",
			GOTSTIM	   = "Picked up a stimpack.",
			GOTMEDINEED   = "Picked up a medikit that you REALLY need!",
			GOTMEDIKIT	= "Picked up a medikit.",
			GOTSUPER	  = "Supercharge!",

			GOTBLUECARD   = "Picked up a blue keycard.",
			GOTYELWCARD   = "Picked up a yellow keycard.",
			GOTREDCARD	= "Picked up a red keycard.",
			GOTBLUESKUL   = "Picked up a blue skull key.",
			GOTYELWSKUL   = "Picked up a yellow skull key.",
			GOTREDSKULL   = "Picked up a red skull key.",

			GOTINVUL	  = "Invulnerability!",
			GOTBERSERK	= "Berserk!",
			GOTINVIS	  = "Partial Invisibility",
			GOTSUIT	   = "Radiation Shielding Suit",
			GOTMAP		= "Computer Area Map",
			GOTVISOR	  = "Light Amplification Visor",
			GOTMSPHERE	= "MegaSphere!",

			GOTCLIP	   = "Picked up a clip.",
			GOTCLIPBOX	= "Picked up a box of bullets.",
			GOTROCKET	 = "Picked up a rocket.",
			GOTROCKBOX	= "Picked up a box of rockets.",
			GOTCELL	   = "Picked up an energy cell.",
			GOTCELLBOX	= "Picked up an energy cell pack.",
			GOTSHELLS	 = "Picked up 4 shotgun shells.",
			GOTSHELLBOX   = "Picked up a box of shotgun shells.",
			GOTBACKPACK   = "Picked up a backpack full of ammo!",

			GOTBFG9000	= "You got the BFG9000!  Oh, yes.",
			GOTCHAINGUN   = "You got the chaingun!",
			GOTCHAINSAW   = "A chainsaw!  Find some meat!",
			GOTLAUNCHER   = "You got the rocket launcher!",
			GOTPLASMA	 = "You got the plasma gun!",
			GOTSHOTGUN	= "You got the shotgun!",
			GOTSHOTGUN2   = "You got the super shotgun!",

			-- P_Doors.C
			PD_BLUEO	  = "You need a blue key to activate this object",
			PD_REDO	   = "You need a red key to activate this object",
			PD_YELLOWO	= "You need a yellow key to activate this object",
			PD_BLUEK	  = "You need a blue key to open this door",
			PD_REDK	  = "You need a red key to open this door",
			PD_YELLOWK	= "You need a yellow key to open this door",

			-- G_game.C
			GGSAVED	   = "game saved.",

			-- HU_stuff.C
			HUSTR_MSGU	= "[Message unsent]",

			HUSTR_E1M1	= "E1M1: Hangar",
			HUSTR_E1M2	= "E1M2: Nuclear Plant",
			HUSTR_E1M3	= "E1M3: Toxin Refinery",
			HUSTR_E1M4	= "E1M4: Command Control",
			HUSTR_E1M5	= "E1M5: Phobos Lab",
			HUSTR_E1M6	= "E1M6: Central Processing",
			HUSTR_E1M7	= "E1M7: Computer Station",
			HUSTR_E1M8	= "E1M8: Phobos Anomaly",
			HUSTR_E1M9	= "E1M9: Military Base",

			HUSTR_E2M1	= "E2M1: Deimos Anomaly",
			HUSTR_E2M2	= "E2M2: Containment Area",
			HUSTR_E2M3	= "E2M3: Refinery",
			HUSTR_E2M4	= "E2M4: Deimos Lab",
			HUSTR_E2M5	= "E2M5: Command Center",
			HUSTR_E2M6	= "E2M6: Halls of the Damned",
			HUSTR_E2M7	= "E2M7: Spawning Vats",
			HUSTR_E2M8	= "E2M8: Tower of Babel",
			HUSTR_E2M9	= "E2M9: Fortress of Mystery",

			HUSTR_E3M1	= "E3M1: Hell Keep",
			HUSTR_E3M2	= "E3M2: Slough of Despair",
			HUSTR_E3M3	= "E3M3: Pandemonium",
			HUSTR_E3M4	= "E3M4: House of Pain",
			HUSTR_E3M5	= "E3M5: Unholy Cathedral",
			HUSTR_E3M6	= "E3M6: Mt. Erebus",
			HUSTR_E3M7	= "E3M7: Limbo",
			HUSTR_E3M8	= "E3M8: Dis",
			HUSTR_E3M9	= "E3M9: Warrens",

			HUSTR_E4M1	= "E4M1: Hell Beneath",
			HUSTR_E4M2	= "E4M2: Perfect Hatred",
			HUSTR_E4M3	= "E4M3: Sever The Wicked",
			HUSTR_E4M4	= "E4M4: Unruly Evil",
			HUSTR_E4M5	= "E4M5: They Will Repent",
			HUSTR_E4M6	= "E4M6: Against Thee Wickedly",
			HUSTR_E4M7	= "E4M7: And Hell Followed",
			HUSTR_E4M8	= "E4M8: Unto The Cruel",
			HUSTR_E4M9	= "E4M9: Fear",

			HUSTR_1	   = "level 1: entryway",
			HUSTR_2	   = "level 2: underhalls",
			HUSTR_3	   = "level 3: the gantlet",
			HUSTR_4	   = "level 4: the focus",
			HUSTR_5	   = "level 5: the waste tunnels",
			HUSTR_6	   = "level 6: the crusher",
			HUSTR_7	   = "level 7: dead simple",
			HUSTR_8	   = "level 8: tricks and traps",
			HUSTR_9	   = "level 9: the pit",
			HUSTR_10	  = "level 10: refueling base",
			HUSTR_11	  = "level 11: 'o' of destruction!",

			HUSTR_12	  = "level 12: the factory",
			HUSTR_13	  = "level 13: downtown",
			HUSTR_14	  = "level 14: the inmost dens",
			HUSTR_15	  = "level 15: industrial zone",
			HUSTR_16	  = "level 16: suburbs",
			HUSTR_17	  = "level 17: tenements",
			HUSTR_18	  = "level 18: the courtyard",
			HUSTR_19	  = "level 19: the citadel",
			HUSTR_20	  = "level 20: gotcha!",

			HUSTR_21	  = "level 21: nirvana",
			HUSTR_22	  = "level 22: the catacombs",
			HUSTR_23	  = "level 23: barrels o' fun",
			HUSTR_24	  = "level 24: the chasm",
			HUSTR_25	  = "level 25: bloodfalls",
			HUSTR_26	  = "level 26: the abandoned mines",
			HUSTR_27	  = "level 27: monster condo",
			HUSTR_28	  = "level 28: the spirit world",
			HUSTR_29	  = "level 29: the living end",
			HUSTR_30	  = "level 30: icon of sin",

			HUSTR_31	  = "level 31: wolfenstein",
			HUSTR_32	  = "level 32: grosse",

			PHUSTR_1	  = "level 1: congo",
			PHUSTR_2	  = "level 2: well of souls",
			PHUSTR_3	  = "level 3: aztec",
			PHUSTR_4	  = "level 4: caged",
			PHUSTR_5	  = "level 5: ghost town",
			PHUSTR_6	  = "level 6: baron's lair",
			PHUSTR_7	  = "level 7: caughtyard",
			PHUSTR_8	  = "level 8: realm",
			PHUSTR_9	  = "level 9: abattoire",
			PHUSTR_10	 = "level 10: onslaught",
			PHUSTR_11	 = "level 11: hunted",

			PHUSTR_12	 = "level 12: speed",
			PHUSTR_13	 = "level 13: the crypt",
			PHUSTR_14	 = "level 14: genesis",
			PHUSTR_15	 = "level 15: the twilight",
			PHUSTR_16	 = "level 16: the omen",
			PHUSTR_17	 = "level 17: compound",
			PHUSTR_18	 = "level 18: neurosphere",
			PHUSTR_19	 = "level 19: nme",
			PHUSTR_20	 = "level 20: the death domain",

			PHUSTR_21	 = "level 21: slayer",
			PHUSTR_22	 = "level 22: impossible mission",
			PHUSTR_23	 = "level 23: tombstone",
			PHUSTR_24	 = "level 24: the final frontier",
			PHUSTR_25	 = "level 25: the temple of darkness",
			PHUSTR_26	 = "level 26: bunker",
			PHUSTR_27	 = "level 27: anti-christ",
			PHUSTR_28	 = "level 28: the sewers",
			PHUSTR_29	 = "level 29: odyssey of noises",
			PHUSTR_30	 = "level 30: the gateway of hell",

			PHUSTR_31	 = "level 31: cyberden",
			PHUSTR_32	 = "level 32: go 2 it",

			THUSTR_1	  = "level 1: system control",
			THUSTR_2	  = "level 2: human bbq",
			THUSTR_3	  = "level 3: power control",
			THUSTR_4	  = "level 4: wormhole",
			THUSTR_5	  = "level 5: hanger",
			THUSTR_6	  = "level 6: open season",
			THUSTR_7	  = "level 7: prison",
			THUSTR_8	  = "level 8: metal",
			THUSTR_9	  = "level 9: stronghold",
			THUSTR_10	 = "level 10: redemption",
			THUSTR_11	 = "level 11: storage facility",

			THUSTR_12	 = "level 12: crater",
			THUSTR_13	 = "level 13: nukage processing",
			THUSTR_14	 = "level 14: steel works",
			THUSTR_15	 = "level 15: dead zone",
			THUSTR_16	 = "level 16: deepest reaches",
			THUSTR_17	 = "level 17: processing area",
			THUSTR_18	 = "level 18: mill",
			THUSTR_19	 = "level 19: shipping/respawning",
			THUSTR_20	 = "level 20: central processing",

			THUSTR_21	 = "level 21: administration center",
			THUSTR_22	 = "level 22: habitat",
			THUSTR_23	 = "level 23: lunar mining project",
			THUSTR_24	 = "level 24: quarry",
			THUSTR_25	 = "level 25: baron's den",
			THUSTR_26	 = "level 26: ballistyx",
			THUSTR_27	 = "level 27: mount pain",
			THUSTR_28	 = "level 28: heck",
			THUSTR_29	 = "level 29: river styx",
			THUSTR_30	 = "level 30: last call",

			THUSTR_31	 = "level 31: pharaoh",
			THUSTR_32	 = "level 32: caribbean",

			HUSTR_CHATMACRO1 = "I'm ready to kick butt!",
			HUSTR_CHATMACRO2 = "I'm OK.",
			HUSTR_CHATMACRO3 = "I'm not looking too good!",
			HUSTR_CHATMACRO4 = "Help!",
			HUSTR_CHATMACRO5 = "You suck!",
			HUSTR_CHATMACRO6 = "Next time, scumbag...",
			HUSTR_CHATMACRO7 = "Come here!",
			HUSTR_CHATMACRO8 = "I'll take care of it.",
			HUSTR_CHATMACRO9 = "Yes",
			HUSTR_CHATMACRO0 = "No",

			HUSTR_TALKTOSELF1 = "You mumble to yourself",
			HUSTR_TALKTOSELF2 = "Who's there?",
			HUSTR_TALKTOSELF3 = "You scare yourself",
			HUSTR_TALKTOSELF4 = "You start to rave",
			HUSTR_TALKTOSELF5 = "You've lost it...",

			HUSTR_MESSAGESENT = "[Message Sent]",

			HUSTR_PLRGREEN = "Green: ",
			HUSTR_PLRINDIGO = "Indigo: ",
			HUSTR_PLRBROWN = "Brown: ",
			HUSTR_PLRRED   = "Red: ",

			HUSTR_KEYGREEN  = "g",
			HUSTR_KEYINDIGO = "i",
			HUSTR_KEYBROWN  = "b",
			HUSTR_KEYRED	= "r",

			-- AM_map.C
			AMSTR_FOLLOWON	= "Follow Mode ON",
			AMSTR_FOLLOWOFF   = "Follow Mode OFF",

			AMSTR_GRIDON	  = "Grid ON",
			AMSTR_GRIDOFF	 = "Grid OFF",

			AMSTR_MARKEDSPOT  = "Marked Spot",
			AMSTR_MARKSCLEARED= "All Marks Cleared",

			-- ST_stuff.C
			STSTR_MUS	   = "Music Change",
			STSTR_NOMUS	 = "IMPOSSIBLE SELECTION",
			STSTR_DQDON	 = "Degreelessness Mode On",
			STSTR_DQDOFF	= "Degreelessness Mode Off",

			STSTR_KFAADDED  = "Very Happy Ammo Added",
			STSTR_FAADDED   = "Ammo (no keys) Added",

			STSTR_NCON	  = "No Clipping Mode ON",
			STSTR_NCOFF	 = "No Clipping Mode OFF",

			STSTR_BEHOLD	= "inVuln, Str, Inviso, Rad, Allmap, or Lite-amp",
			STSTR_BEHOLDX   = "Power-up Toggled",

			STSTR_CHOPPERS  = "... doesn't suck - GM",
			STSTR_CLEV	  = "Changing Level...",

			CC_ZOMBIE	   = "ZOMBIEMAN",
			CC_SHOTGUN	  = "SHOTGUN GUY",
			CC_HEAVY		= "HEAVY WEAPON DUDE",
			CC_IMP		  = "IMP",
			CC_DEMON		= "DEMON",
			CC_LOST		 = "LOST SOUL",
			CC_CACO		 = "CACODEMON",
			CC_HELL		 = "HELL KNIGHT",
			CC_BARON		= "BARON OF HELL",
			CC_ARACH		= "ARACHNOTRON",
			CC_PAIN		 = "PAIN ELEMENTAL",
			CC_REVEN		= "REVENANT",
			CC_MANCU		= "MANCUBUS",
			CC_ARCH		 = "ARCH-VILE",
			CC_SPIDER	   = "THE SPIDER MASTERMIND",
			CC_CYBER		= "THE CYBERDEMON",
			CC_HERO		 = "OUR HERO",

			E1TEXT = "Once you beat the big badasses and\nclean out the moon base you're supposed\nto win, aren't you? Aren't you? Where's\nyour fat reward and ticket home? What\nthe hell is this? It's not supposed to\nend this way!\n\nIt stinks like rotten meat, but looks\nlike the lost Deimos base.  Looks like\nyou're stuck on The Shores of Hell.\nThe only way out is through.\n\nTo continue the DOOM experience, play\nThe Shores of Hell and its amazing\nsequel, Inferno!\n",
			E2TEXT = "You've done it! The hideous cyber-\ndemon lord that ruled the lost Deimos\nmoon base has been slain and you\nare triumphant! But ... where are\nyou? You clamber to the edge of the\nmoon and look down to see the awful\ntruth.\n\nDeimos floats above Hell itself!\nYou've never heard of anyone escaping\nfrom Hell, but you'll make the bastards\nsorry they ever heard of you! Quickly,\nyou rappel down to  the surface of\nHell.\n\nNow, it's on to the final chapter of\nDOOM! -- Inferno.",
			E3TEXT = "The loathsome spiderdemon that\nmasterminded the invasion of the moon\nbases and caused so much death has had\nits ass kicked for all time.\n\nA hidden doorway opens and you enter.\nYou've proven too tough for Hell to\ncontain, and now Hell at last plays\nfair -- for you emerge from the door\nto see the green fields of Earth!\nHome at last.\n\nYou wonder what's been happening on\nEarth while you were battling evil\nunleashed. It's good that no Hell-\nspawn could have come through that\ndoor with you ...",
			E4TEXT = "the spider mastermind must have sent forth\nits legions of hellspawn before your\nfinal confrontation with that terrible\nbeast from hell.  but you stepped forward\nand brought forth eternal damnation and\nsuffering upon the horde as a true hero\nwould in the face of something so evil.\n\nbesides, someone was gonna pay for what\nhappened to daisy, your pet rabbit.\n\nbut now, you see spread before you more\npotential pain and gibbitude as a nation\nof demons run amok among our cities.\n\nnext stop, hell on earth!",
			C1TEXT = "YOU HAVE ENTERED DEEPLY INTO THE INFESTED\nSTARPORT. BUT SOMETHING IS WRONG. THE\nMONSTERS HAVE BROUGHT THEIR OWN REALITY\nWITH THEM, AND THE STARPORT'S TECHNOLOGY\nIS BEING SUBVERTED BY THEIR PRESENCE.\n\nAHEAD, YOU SEE AN OUTPOST OF HELL, A\nFORTIFIED ZONE. IF YOU CAN GET PAST IT,\nYOU CAN PENETRATE INTO THE HAUNTED HEART\nOF THE STARBASE AND FIND THE CONTROLLING\nSWITCH WHICH HOLDS EARTH'S POPULATION\nHOSTAGE.",
			C2TEXT = "YOU HAVE WON! YOUR VICTORY HAS ENABLED\nHUMANKIND TO EVACUATE EARTH AND ESCAPE\nTHE NIGHTMARE.  NOW YOU ARE THE ONLY\nHUMAN LEFT ON THE FACE OF THE PLANET.\nCANNIBAL MUTATIONS, CARNIVOROUS ALIENS,\nAND EVIL SPIRITS ARE YOUR ONLY NEIGHBORS.\nYOU SIT BACK AND WAIT FOR DEATH, CONTENT\nTHAT YOU HAVE SAVED YOUR SPECIES.\n\nBUT THEN, EARTH CONTROL BEAMS DOWN A\nMESSAGE FROM SPACE: \"SENSORS HAVE LOCATED\nTHE SOURCE OF THE ALIEN INVASION. IF YOU\nGO THERE, YOU MAY BE ABLE TO BLOCK THEIR\nENTRY.  THE ALIEN BASE IS IN THE HEART OF\nYOUR OWN HOME CITY, NOT FAR FROM THE\nSTARPORT.\" SLOWLY AND PAINFULLY YOU GET\nUP AND RETURN TO THE FRAY.",
			C3TEXT = "YOU ARE AT THE CORRUPT HEART OF THE CITY,\nSURROUNDED BY THE CORPSES OF YOUR ENEMIES.\nYOU SEE NO WAY TO DESTROY THE CREATURES'\nENTRYWAY ON THIS SIDE, SO YOU CLENCH YOUR\nTEETH AND PLUNGE THROUGH IT.\n\nTHERE MUST BE A WAY TO CLOSE IT ON THE\nOTHER SIDE. WHAT DO YOU CARE IF YOU'VE\nGOT TO GO THROUGH HELL TO GET TO IT?",
			C4TEXT = "THE HORRENDOUS VISAGE OF THE BIGGEST\nDEMON YOU'VE EVER SEEN CRUMBLES BEFORE\nYOU, AFTER YOU PUMP YOUR ROCKETS INTO\nHIS EXPOSED BRAIN. THE MONSTER SHRIVELS\nUP AND DIES, ITS THRASHING LIMBS\nDEVASTATING UNTOLD MILES OF HELL'S\nSURFACE.\n\nYOU'VE DONE IT. THE INVASION IS OVER.\nEARTH IS SAVED. HELL IS A WRECK. YOU\nWONDER WHERE BAD FOLKS WILL GO WHEN THEY\nDIE, NOW. WIPING THE SWEAT FROM YOUR\nFOREHEAD YOU BEGIN THE LONG TREK BACK\nHOME. REBUILDING EARTH OUGHT TO BE A\nLOT MORE FUN THAN RUINING IT WAS.\n",
			C5TEXT = "CONGRATULATIONS, YOU'VE FOUND THE SECRET\nLEVEL! LOOKS LIKE IT'S BEEN BUILT BY\nHUMANS, RATHER THAN DEMONS. YOU WONDER\nWHO THE INMATES OF THIS CORNER OF HELL\nWILL BE.",
			C6TEXT = "CONGRATULATIONS, YOU'VE FOUND THE\nSUPER SECRET LEVEL!  YOU'D BETTER\nBLAZE THROUGH THIS ONE!\n",
			T1TEXT = "You've fought your way out of the infested\nexperimental labs.   It seems that UAC has\nonce again gulped it down.  With their\nhigh turnover, it must be hard for poor\nold UAC to buy corporate health insurance\nnowadays..\n\nAhead lies the military complex, now\nswarming with diseased horrors hot to get\ntheir teeth into you. With luck, the\ncomplex still has some warlike ordnance\nlaying around.",
			T2TEXT = "You hear the grinding of heavy machinery\nahead.  You sure hope they're not stamping\nout new hellspawn, but you're ready to\nream out a whole herd if you have to.\nThey might be planning a blood feast, but\nyou feel about as mean as two thousand\nmaniacs packed into one mad killer.\n\nYou don't plan to go down easy.",
			T3TEXT = "The vista opening ahead looks real damn\nfamiliar. Smells familiar, too -- like\nfried excrement. You didn't like this\nplace before, and you sure as hell ain't\nplanning to like it now. The more you\nbrood on it, the madder you get.\nHefting your gun, an evil grin trickles\nonto your face. Time to take some names.",
			T4TEXT = "Suddenly, all is silent, from one horizon\nto the other. The agonizing echo of Hell\nfades away, the nightmare sky turns to\nblue, the heaps of monster corpses start \nto evaporate along with the evil stench \nthat filled the air. Jeeze, maybe you've\ndone it. Have you really won?\n\nSomething rumbles in the distance.\nA blue light begins to glow inside the\nruined skull of the demon-spitter.",
			T5TEXT = "What now? Looks totally different. Kind\nof like King Tut's condo. Well,\nwhatever's here can't be any worse\nthan usual. Can it?  Or maybe it's best\nto let sleeping gods lie..",
			T6TEXT = "Time for a vacation. You've burst the\nbowels of hell and by golly you're ready\nfor a break. You mutter to yourself,\nMaybe someone else can kick Hell's ass\nnext time around. Ahead lies a quiet town,\nwith peaceful flowing water, quaint\nbuildings, and presumably no Hellspawn.\n\nAs you step off the transport, you hear\nthe stomp of a cyberdemon's iron shoe.",
		}
	elseif gameType == "chex" then
		doom.strings = {
			-- P_inter.C
			GOTARMOR	  = "Picked up the Chex(R) Armor.",
			GOTMEGA	   = "Picked up the Super Chex(R) Armor!",
			GOTHTHBONUS   = "Picked up a glass of water.",
			GOTARMBONUS   = "Picked up slime repellent.",
			GOTSTIM	   = "Picked up a bowl of fruit.",
			GOTMEDINEED   = "Picked up some needed vegetables!",
			GOTMEDIKIT	= "Picked up a bowl of vegetables.",
			GOTSUPER	  = "Supercharge Breakfast!",

			GOTBLUECARD   = "Picked up a blue key.",
			GOTYELWCARD   = "Picked up a yellow key.",
			GOTREDCARD	= "Picked up a red key.",
			GOTBLUESKUL   = "Picked up a blue skull key.",
			GOTYELWSKUL   = "Picked up a yellow skull key.",
			GOTREDSKULL   = "Picked up a red skull key.",

			GOTINVUL	  = "Invulnerability!",
			GOTBERSERK	= "Berserk!",
			GOTINVIS	  = "Partial Invisibility",
			GOTSUIT	   = "Slimeproof Suit",
			GOTMAP		= "Computer Area Map",
			GOTVISOR	  = "Light Amplification Visor",
			GOTMSPHERE	= "MegaSphere!",

			GOTCLIP	   = "Picked up a mini zorch recharge.",
			GOTCLIPBOX	= "Picked up a mini zorch pack.",
			GOTROCKET	 = "Picked up a zorch propulsor recharge.",
			GOTROCKBOX	= "Picked up a zorch propulsor pack.",
			GOTCELL	   = "Picked up a phasing zorcher recharge.",
			GOTCELLBOX	= "Picked up a phasing zorcher pack.",
			GOTSHELLS	 = "Picked up a large zorcher recharge.",
			GOTSHELLBOX   = "Picked up a large zorcher pack.",
			GOTBACKPACK   = "Picked up a Zorchpak!",

			GOTBFG9000	= "You got the LAZ Device!",
			GOTCHAINGUN   = "You got the Rapid Zorcher!",
			GOTCHAINSAW   = "You got the Super Bootspork!",
			GOTLAUNCHER   = "You got the Zorch Propulsor!",
			GOTPLASMA	 = "You got the Phasing Zorcher!",
			GOTSHOTGUN	= "You got the Large Zorcher!",
			GOTSHOTGUN2   = "You got the Super Large Zorcher!",

			-- P_Doors.C
			PD_BLUEO	  = "You need a blue key to activate this object",
			PD_REDO	   = "You need a red key to activate this object",
			PD_YELLOWO	= "You need a yellow key to activate this object",
			PD_BLUEK	  = "You need a blue key to open this door",
			PD_REDK	   = "You need a red key to open this door",
			PD_YELLOWK	= "You need a yellow key to open this door",

			-- G_game.C
			GGSAVED	   = "game saved.",

			-- HU_stuff.C
			HUSTR_MSGU	= "[Message unsent]",

			HUSTR_E1M1	= "E1M1: Landing Zone",
			HUSTR_E1M2	= "E1M2: Storage Facility",
			HUSTR_E1M3	= "E1M3: Experimental Lab",
			HUSTR_E1M4	= "E1M4: Arboretum",
			HUSTR_E1M5	= "E1M5: Caverns of Bazoik",
			HUSTR_E1M6	= "E1M6: Central Processing",
			HUSTR_E1M7	= "E1M7: Computer Station",
			HUSTR_E1M8	= "E1M8: Phobos Anomaly",
			HUSTR_E1M9	= "E1M9: Military Base",

			HUSTR_E2M1	= "E2M1: Deimos Anomaly",
			HUSTR_E2M2	= "E2M2: Containment Area",
			HUSTR_E2M3	= "E2M3: Refinery",
			HUSTR_E2M4	= "E2M4: Deimos Lab",
			HUSTR_E2M5	= "E2M5: Command Center",
			HUSTR_E2M6	= "E2M6: Halls of the Damned",
			HUSTR_E2M7	= "E2M7: Spawning Vats",
			HUSTR_E2M8	= "E2M8: Tower of Babel",
			HUSTR_E2M9	= "E2M9: Fortress of Mystery",

			HUSTR_E3M1	= "E3M1: Hell Keep",
			HUSTR_E3M2	= "E3M2: Slough of Despair",
			HUSTR_E3M3	= "E3M3: Pandemonium",
			HUSTR_E3M4	= "E3M4: House of Pain",
			HUSTR_E3M5	= "E3M5: Unholy Cathedral",
			HUSTR_E3M6	= "E3M6: Mt. Erebus",
			HUSTR_E3M7	= "E3M7: Limbo",
			HUSTR_E3M8	= "E3M8: Dis",
			HUSTR_E3M9	= "E3M9: Warrens",

			HUSTR_E4M1	= "E4M1: Hell Beneath",
			HUSTR_E4M2	= "E4M2: Perfect Hatred",
			HUSTR_E4M3	= "E4M3: Sever The Wicked",
			HUSTR_E4M4	= "E4M4: Unruly Evil",
			HUSTR_E4M5	= "E4M5: They Will Repent",
			HUSTR_E4M6	= "E4M6: Against Thee Wickedly",
			HUSTR_E4M7	= "E4M7: And Hell Followed",
			HUSTR_E4M8	= "E4M8: Unto The Cruel",
			HUSTR_E4M9	= "E4M9: Fear",

			HUSTR_CHATMACRO1 = "I'm ready to zorch!",
			HUSTR_CHATMACRO2 = "I'm feeling great!",
			HUSTR_CHATMACRO3 = "I'm getting pretty gooed up!",
			HUSTR_CHATMACRO4 = "Somebody help me!",
			HUSTR_CHATMACRO5 = "Go back to your own dimension!",
			HUSTR_CHATMACRO6 = "Stop that Flemoid",
			HUSTR_CHATMACRO7 = "I think I'm lost!",
			HUSTR_CHATMACRO8 = "I'll get you out of this gunk.",
			HUSTR_CHATMACRO9 = "Yes",
			HUSTR_CHATMACRO0 = "No",

			HUSTR_TALKTOSELF1 = "I'm feeling great.",
			HUSTR_TALKTOSELF2 = "I think I'm lost.",
			HUSTR_TALKTOSELF3 = "Oh No...",
			HUSTR_TALKTOSELF4 = "Gotta break free.",
			HUSTR_TALKTOSELF5 = "Hurry!",

			HUSTR_MESSAGESENT = "[Message Sent]",

			HUSTR_PLRGREEN = "Green: ",
			HUSTR_PLRINDIGO = "Indigo: ",
			HUSTR_PLRBROWN = "Brown: ",
			HUSTR_PLRRED   = "Red: ",

			HUSTR_KEYGREEN  = "g",
			HUSTR_KEYINDIGO = "i",
			HUSTR_KEYBROWN  = "b",
			HUSTR_KEYRED	= "r",

			-- AM_map.C
			AMSTR_FOLLOWON	= "Follow Mode ON",
			AMSTR_FOLLOWOFF   = "Follow Mode OFF",

			AMSTR_GRIDON	  = "Grid ON",
			AMSTR_GRIDOFF	 = "Grid OFF",

			AMSTR_MARKEDSPOT  = "Marked Spot",
			AMSTR_MARKSCLEARED= "All Marks Cleared",

			-- ST_stuff.C
			STSTR_MUS	   = "Music Change",
			STSTR_NOMUS	 = "IMPOSSIBLE SELECTION",
			STSTR_DQDON	 = "Invincible Mode On",
			STSTR_DQDOFF	= "Invincible Mode Off",

			STSTR_KFAADDED  = "Super Zorch Added",
			STSTR_FAADDED   = "Zorch Added",

			STSTR_NCON	  = "No Clipping Mode ON",
			STSTR_NCOFF	 = "No Clipping Mode OFF",

			STSTR_BEHOLD	= "inVuln, Str, Inviso, Rad, Allmap, or Lite-amp",
			STSTR_BEHOLDX   = "Power-up Toggled",

			STSTR_CHOPPERS  = "... Eat Chex(R)!",
			STSTR_CLEV	  = "Changing Level...",
			
			CHEXWIN		 = [[Mission accomplished.

						Are you prepared for the next mission?






						Press the escape key to continue...]]
		}
	end
end