dofile("strifeData/Definitions/Inventory/Ammo.lua")
dofile("strifeData/Definitions/Inventory/Weps.lua")
dofile("strifeData/Definitions/Objects/Deco.lua")
dofile("strifeData/Definitions/Objects/Actors/Beggars.lua")
dofile("strifeData/Definitions/Objects/Actors/Peasants.lua")
dofile("strifeData/Definitions/Objects/Actors/Acolytes.lua")
dofile("strifeData/Definitions/Objects/Actors/Alarm.lua")
dofile("strifeData/Definitions/Objects/Actors/Macil.lua")
dofile("strifeData/Definitions/Objects/Items/Gold.lua")
dofile("strifeData/Definitions/Objects/Items/ClipOfBullets.lua")
dofile("strifeData/Definitions/Objects/Items/BoxOfBullets.lua")
dofile("strifeData/Definitions/Objects/Items/MedPatch.lua")
dofile("strifeData/Definitions/Objects/Items/MedicalKit.lua")
dofile("strifeData/Definitions/Objects/Items/OfferingChalice.lua")
dofile("strifeData/Definitions/Objects/Items/MiniMissiles.lua")

dofile("strifeData/HUD/HUD.lua")