dofile(doom.currentGame .. "DataDefinitions/Inventory/Ammo.lua")
dofile(doom.currentGame .. "DataDefinitions/Inventory/Weps.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Deco.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Actors/Beggars.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Actors/Peasants.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Actors/Acolytes.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Actors/Alarm.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Actors/Macil.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Items/Gold.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Items/ClipOfBullets.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Items/BoxOfBullets.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Items/MedPatch.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Items/MedicalKit.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Items/OfferingChalice.lua")
dofile(doom.currentGame .. "DataDefinitions/Objects/Items/MiniMissiles.lua")

dofile(doom.currentGame .. "Data/HUD/HUD.lua")