"""
PK3/ZIP processing functions.
"""

import os
import re
import zipfile
import tempfile
from pathlib import Path
from modules.wad_processor import (
	make_cycle_sequence, convert_exmx_maps,
	patch_linedefs_add, process_udmf_map_linedefs,
	parse_soc_templates, DOOM2_SOC_TEXT, generate_soc_patch,
	append_stcfn_uppercase_to_lowercase
)
from modules.utils import CUTSCENE_GRAPHICS
from modules.umapinfo_processor import MAPINFOProcessor
from omg import WAD
import glob

def extract_stcfn_lumps(wad, graphics_dir):
	"""Extract all STCFN lumps from wad.graphics to graphics_dir as .lmp files,
	then remove them from the WAD.
	"""
	stcfn_keys = [name for name in wad.graphics]
	if not stcfn_keys:
		return

	os.makedirs(graphics_dir, exist_ok=True)

	for name in stcfn_keys:
		lump = wad.graphics[name]

		# Remove any existing file with this lump name, regardless of extension
		for conflict in glob.glob(os.path.join(graphics_dir, name + "*")):
			print(f"Removed conflicting lump '{os.path.basename(conflict)}'")
			os.remove(conflict)

		# Write as .lmp
		file_path = os.path.join(graphics_dir, f"{name}.lmp")
		with open(file_path, 'wb') as f:
			f.write(lump.data)

		print(f"  Extracted STCFN lump {name} -> Graphics/{name}.lmp")

		# Remove from WAD
		del wad.graphics[name]

def process_pk3_file(src_pk3_path, out_pk3_path):
	"""Process a PK3 file with WAD-like operations and Lua generation."""
	print(f"Processing PK3: {src_pk3_path}")
	
	with tempfile.TemporaryDirectory() as temp_dir:
		with zipfile.ZipFile(src_pk3_path, 'r') as zip_ref:
			zip_ref.extractall(temp_dir)
		
		wad_files_processed = 0
		lua_content_lines = []
		soc_content_lines = []
		external_umapinfo_text = None
		external_umapinfo_format = None

		for root, dirs, files in os.walk(temp_dir):
			for file in files:
				stem = Path(file).stem.upper()
				if stem in ("UMAPINFO", "MAPINFO") and external_umapinfo_text is None:
					file_path = os.path.join(root, file)
					try:
						raw_bytes = open(file_path, 'rb').read()
						external_umapinfo_text = raw_bytes.decode('utf-8-sig', errors='replace')
						external_umapinfo_format = 'mapinfo' if stem == 'MAPINFO' else 'umapinfo'
						print(f"  Found external {stem} in PK3 source")
					except Exception as e:
						print(f"  Failed reading external {file}: {e}")

		base_templates = parse_soc_templates(DOOM2_SOC_TEXT)

		if external_umapinfo_text and MAPINFOProcessor is not None:
			try:
				processor = MAPINFOProcessor(external_umapinfo_text, format=external_umapinfo_format)
				processor.parse()
				print(f"  Parsed {len(processor.maps)} map definitions from {external_umapinfo_format.upper()}")
				
				# Generate SOC patch
				soc_content = generate_soc_patch(processor, base_templates)
				if soc_content:
					soc_content_lines.append(soc_content)
					print(f"  Generated SOC content from MAPINFO")
			except Exception as e:
				print(f"  Error processing MAPINFO: {e}")

		external_umapinfo_text = None
		external_umapinfo_format = None

		for root, dirs, files in os.walk(temp_dir):
			for file in files:
				file_path = os.path.join(root, file)

				if file.lower().endswith('.wad'):
					rel_path = os.path.relpath(file_path, temp_dir).replace('\\', '/')
					is_pk3_map = rel_path.lower().startswith('maps/')

					try:
						print(f"  Processing WAD: {file}")

						wad = WAD()
						wad.from_file(file_path)

						if is_pk3_map:
							# PK3 map WADs need to behave like maps, not PWADs.
							# Restore the map header from the filename.
							map_name = Path(file).stem.upper()

							if map_name in wad.maps:
								# Already named correctly
								pass
							elif len(wad.maps) == 1:
								# omg.WAD often loads unnamed map WADs as the only entry.
								old_name = next(iter(wad.maps))
								wad.maps[map_name] = wad.maps.pop(old_name)

							print(f"	Treating {file} as map {map_name}")

							patch_linedefs_add(wad, 941)
							print("\tPatched linedef specials (+941)")

						else:
							# Normal external PWAD handling
							append_stcfn_uppercase_to_lowercase(wad)

							created = make_cycle_sequence(wad, wad, "FWATER", 1, 16, 1, 4)
							if created > 0:
								print(f"\tCreated {created} FWATER textures")

							converted = convert_exmx_maps(
								wad,
								wad,
								file_path
							)
							if converted > 0:
								print(f"\tConverted {converted} ExMx maps")

							for map_name in wad.maps:
								wad.maps[map_name] = process_udmf_map_linedefs(
									wad.maps[map_name],
									941
								)

						wad.to_file(file_path)
						wad_files_processed += 1

					except Exception as e:
						import traceback
						traceback.print_exc()
						print(f"\tError processing WAD {file}: {e}")

		if soc_content_lines:
			# Create SOC directory if it doesn't exist
			soc_dir = os.path.join(temp_dir, 'SOC')
			if not os.path.exists(soc_dir):
				os.makedirs(soc_dir)
			
			# Write main SOC file
			soc_content = '\n'.join(soc_content_lines)
			soc_path = os.path.join(soc_dir, 'AutoGenerated.soc')
			with open(soc_path, 'w', encoding='utf-8') as f:
				f.write(soc_content)
			print(f"  Created SOC/AutoGenerated.soc with {len(soc_content_lines)} lines")
		
		lua_dir = os.path.join(temp_dir, 'Lua')
		if lua_content_lines and not os.path.exists(lua_dir):
			os.makedirs(lua_dir)
		
		if lua_content_lines:
			mapdata_content = '\n'.join(lua_content_lines)
			mapdata_path = os.path.join(temp_dir, 'MapData.lua')
			with open(mapdata_path, 'w') as f:
				f.write(mapdata_content)
			print(f"  Created MapData.lua with {len(lua_content_lines)} lines")
		
		if lua_content_lines:
			lua_file_path = os.path.join(lua_dir, 'AutoGeneratedMaps.lua')
			with open(lua_file_path, 'w') as f:
				f.write(mapdata_content)
			print(f"  Created Lua/AutoGeneratedMaps.lua")
		
		graphics_dir = os.path.join(temp_dir, 'Graphics')
		if not os.path.exists(graphics_dir):
			os.makedirs(graphics_dir)

		wad = WAD()
		append_stcfn_uppercase_to_lowercase(wad)
		extract_stcfn_lumps(wad, graphics_dir)

		# Convert Graphics/*.png files to LMP patch files so PK3 sources
		# get the same PNG->LMP conversion as WAD-based workflows.
		try:
			from modules.pngtopatch import (
				resolve_palette_bytes,
				png_file_to_patch,
				should_convert_graphics_png,
			)

			project_root = os.path.dirname(src_pk3_path)
			for root, dirs, files in os.walk(temp_dir):
				for filename in list(files):
					rel = os.path.relpath(os.path.join(root, filename), temp_dir).replace('\\', '/')
					if not filename.lower().endswith('.png'):
						continue
					if not should_convert_graphics_png(rel, source=src_pk3_path):
						continue

					fullpath = os.path.join(root, filename)
					try:
						with open(fullpath, 'rb') as f:
							png_data = f.read()

						if not png_data.startswith(b'\x89PNG\r\n\x1a\n'):
							print(f"Skipped non-PNG data for {rel}")
							continue

						palette = resolve_palette_bytes(project_root, wad=None)
						patch = png_file_to_patch(fullpath, palette)
						out_name = os.path.splitext(filename)[0] + '.lmp'
						out_path = os.path.join(root, out_name)
						with open(out_path, 'wb') as f:
							f.write(patch.toBytes())
						try:
							os.remove(fullpath)
						except Exception:
							pass
						print(f"Converted PNG -> LMP: {rel} -> {out_name}")
					except Exception as e:
						print(f"Failed converting PNG {rel}: {e}")
		except Exception:
			pass
		
		for root, dirs, files in os.walk(temp_dir):
			for file in files:
				file_path = os.path.join(root, file)
				if file.lower().endswith('.wad'):
					continue
					
				for flat_name, graphic_name in CUTSCENE_GRAPHICS:
					if file.upper() == flat_name:
						try:
							with open(file_path, 'rb') as f:
								flat_data = f.read()
							
							if len(flat_data) >= 4096:
								from modules.wad_processor import convert_flat_to_graphic
								graphic_lump = convert_flat_to_graphic(flat_data, graphic_name)
								graphic_path = os.path.join(graphics_dir, graphic_name)
								with open(graphic_path, 'wb') as f:
									f.write(graphic_lump.data)
								print(f"  Created Graphics/{graphic_name} from loose flat {file}")
						except Exception as e:
							print(f"  Error converting loose flat {file}: {e}")
		
		with zipfile.ZipFile(out_pk3_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
			for root, dirs, files in os.walk(temp_dir):
				for file in files:
					file_path = os.path.join(root, file)
					arcname = os.path.relpath(file_path, temp_dir)
					zipf.write(file_path, arcname)
		
		print(f"  Processed {wad_files_processed} WAD files")
		print(f"  Created PK3: {out_pk3_path}")

def _wad_group_to_bytes(group, wad_type='PWAD', header_name=None):
	"""Serialize a NameGroup, WAD map object, or lump collection into WAD bytes.

	If a lump named '_HEADER_' exists and `header_name` is provided, the lump
	will be renamed to `header_name` (truncated/padded to 8 chars) in the
	serialized WAD directory so map headers use the actual map name.
	"""
	from io import BytesIO

	if hasattr(group, 'data') and not isinstance(group, dict):
		group = group.data

	entries = []
	for lump_name, lump in group.items():
		if hasattr(lump, 'data'):
			data = lump.data
		elif isinstance(lump, (bytes, bytearray)):
			data = bytes(lump)
		else:
			raise TypeError(f"Unsupported lump object for {lump_name}: {type(lump)}")

		if not isinstance(data, (bytes, bytearray)):
			raise TypeError(f"Lump data for {lump_name} is not bytes")

		lump_name = lump_name.upper()
		# If this lump is the placeholder header, and a real header name was
		# provided, use that instead so maps inside PK3s have named headers
		# like MAP01, MAP02, etc.
		if lump_name == '_HEADER_' and header_name:
			lump_name = header_name.upper()
		if len(lump_name) > 8:
			lump_name = lump_name[:8]
		lump_name_bytes = lump_name.encode('ascii', 'replace').ljust(8, b'\x00')
		entries.append((lump_name_bytes, bytes(data)))

	data_offset = 12
	for _, data in entries:
		data_offset += len(data)
	directory_offset = data_offset

	buffer = BytesIO()
	buffer.write(wad_type.encode('ascii'))
	buffer.write(len(entries).to_bytes(4, 'little'))
	buffer.write(directory_offset.to_bytes(4, 'little'))

	for _, data in entries:
		buffer.write(data)

	current_offset = 12
	for lump_name_bytes, data in entries:
		buffer.write(current_offset.to_bytes(4, 'little'))
		buffer.write(len(data).to_bytes(4, 'little'))
		buffer.write(lump_name_bytes)
		current_offset += len(data)

	return buffer.getvalue()


def wad_to_pk3(wad, pk3_path):
	"""
	Convert a WAD to PK3 format with proper directory structure.
	"""
	print(f"Converting WAD to PK3: {pk3_path}")
	
	pathlookup = {
		'Sprites': 'Sprites/',
		'Patches': 'Patches/', 
		'Flats': 'Flats/',
		'Colormaps': 'Colormaps/',
		'Ztextures': 'Textures/',
		'Maps': 'Maps/',
		'GLMaps': 'Maps/',
		'Music': 'Music/',
		'Sounds': 'Sounds/',
		'Txdefs': '',
		'Graphics': 'Graphics/',
		'Data': ''
	}
	
	alt_lua_names = {
		'DOOM': 'DoomMarker',
		'ENDM': 'Endoom',
		'DEH': 'DehLanguageBex',
		'UMAP': 'UMapInfo',
	}

	alt_soc_names = {
		'UMAP': 'SOC_UMapInfo',
	}
	
	with zipfile.ZipFile(pk3_path, 'w', zipfile.ZIP_DEFLATED) as pk3:
		for map_name, map_data in wad.maps.items():
			wad_bytes = _wad_group_to_bytes(map_data, wad_type='PWAD', header_name=map_name)
			pk3.writestr(f"Maps/{map_name}.wad", wad_bytes)
			#print(f"  Added map: Maps/{map_name}.wad")
			
		groups = {
			'Sprites': wad.sprites,
			'Patches': wad.patches,
			'Flats': wad.flats,
			'Colormaps': wad.colormaps,
			'Ztextures': wad.ztextures,
			'Music': wad.music,
			'Sounds': wad.sounds,
			'Txdefs': wad.txdefs,
			'Graphics': wad.graphics,
			'Data': wad.data
		}
			
		lua_lumps = {}
		soc_lumps = {}
		player_sprite_lumps = {}
		p_skin_lump = None
		player_sprite_states = ['STND', 'WALK', 'FIRE', 'FLSH', 'PAIN', 'DYIN', 'DEAD', 'GIBN', 'GIBD']
		
		for group_name, group in groups.items():
			for lump_name, lump in group.items():
				if group_name == 'maps':
					continue
					
				if lump_name.startswith('LUA_'):
					lua_lumps[lump_name] = lump
					continue
				if lump_name.startswith('SOC_'):
					soc_lumps[lump_name] = lump
					continue
				
				if lump_name == 'P_SKIN':
					p_skin_lump = lump
					continue
				
				if group_name == 'Data':
					is_player_sprite = False
					for state in player_sprite_states:
						if lump_name.startswith(state):
							if len(lump_name) > len(state):
								next_char = lump_name[len(state)]
								if next_char in 'ABCDEFGHIJKLMNOPQRSTUVW':
									is_player_sprite = True
									break
					
					if is_player_sprite:
						player_sprite_lumps[lump_name] = lump
						continue
				
				path_prefix = pathlookup.get(group_name, '')
				if path_prefix:
					full_path = f"{path_prefix}{lump_name}"
				else:
					full_path = lump_name
				
				pk3.writestr(full_path, lump.data)
				#print(f"  Added {full_path}")
		
		for lua_name, lua_lump in lua_lumps.items():
			lua_filename = lua_name[4:] if lua_name.startswith('LUA_') else lua_name
			if lua_filename in alt_lua_names:
				lua_filename = alt_lua_names[lua_filename]
			pk3.writestr(f"Lua/{lua_filename}.lua", lua_lump.data)
			#print(f"  Added Lua/{lua_filename}.lua")
		
		for soc_name, soc_lump in soc_lumps.items():
			soc_filename = soc_name[4:] if soc_name.startswith('SOC_') else soc_name
			if soc_filename in alt_soc_names:
				soc_filename = alt_soc_names[soc_filename]
			pk3.writestr(f"SOC/{soc_filename}", soc_lump.data)
			#print(f"  Added SOC/{soc_filename}")
		
		if p_skin_lump or player_sprite_lumps:
			#print("  Adding player sprites to Skins/ directory structure...")
			
			if p_skin_lump:
				pk3.writestr("Skins/1 - P_SKIN/P_SKIN", p_skin_lump.data)
				#print(f"	Added Skins/1 - P_SKIN/P_SKIN")
			
			if player_sprite_lumps:
					for sprite_name, sprite_lump in player_sprite_lumps.items():
						pk3.writestr(f"Skins/2 - Sprites/{sprite_name}", sprite_lump.data)
						#print(f"	Added Skins/2 - Sprites/{sprite_name}")
	
	print(f"Created PK3: {pk3_path}")