-- This ordering sucks, but it keeps states later down the line from complaining
/*
dofile(doom.currentGame .. "Data/Definitions/Objects/Projectiles/Rocket.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Projectiles/Imp Fireball.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Projectiles/Mancubus Fireball.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Projectiles/Cacodemon Shot.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Projectiles/Plasma.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Projectiles/Arachnotron Plasma.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Projectiles/Revenant Projectile.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Projectiles/BOH Fireball.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Projectiles/BFG Ball.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Effects/Telefog.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Effects/Bullet Puff.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Effects/Revenant Tracer.lua")
dofile(doom.currentGame .. "Data/Definitions/Inventory/Ammo.lua")
dofile(doom.currentGame .. "Data/Definitions/Inventory/Weps.lua")
dofile(doom.currentGame .. "Data/Definitions/Inventory/Weps-Ringslinger.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Deco.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Artifacts/Invuln.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Artifacts/Berserk.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Artifacts/Megasphere.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Artifacts/Blursphere.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Artifacts/Radiation Suit.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Artifacts/Soulsphere.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Artifacts/Backpack.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Artifacts/ComputerAreaMap.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Artifacts/Lite-Amp.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Items/Ammo.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Items/Armor.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Items/Health.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Items/Weapons.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Keycards/Yellow Key.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Keycards/Blue Key.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Keycards/Red Key.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Keycards/Yellow Skull Key.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Keycards/Blue Skull Key.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Keycards/Red Skull Key.lua")
dofile(doom.currentGame .. "Data/Definitions/Objects/Monsters/RomeroHead.lua")
*/
dofile(doom.currentGame .. "Data/Definitions/States/Player.lua")
--dofile(doom.currentGame .. "Data/Definitions/Objects/MiscDeco.lua")

dofile(doom.currentGame .. "Data/HUD/HUD.lua")