-- This ordering sucks, but it keeps states later down the line from complaining
dofile("doomData/Definitions/Objects/Projectiles/Rocket.lua")
dofile("doomData/Definitions/Objects/Projectiles/Imp Fireball.lua")
dofile("doomData/Definitions/Objects/Projectiles/Mancubus Fireball.lua")
dofile("doomData/Definitions/Objects/Projectiles/Cacodemon Shot.lua")
dofile("doomData/Definitions/Objects/Projectiles/Plasma.lua")
dofile("doomData/Definitions/Objects/Projectiles/Arachnotron Plasma.lua")
dofile("doomData/Definitions/Objects/Projectiles/Revenant Projectile.lua")
dofile("doomData/Definitions/Objects/Projectiles/BOH Fireball.lua")
dofile("doomData/Definitions/Objects/Projectiles/BFG Ball.lua")
dofile("doomData/Definitions/Objects/Effects/Telefog.lua")
dofile("doomData/Definitions/Objects/Effects/Itemfog.lua")
dofile("doomData/Definitions/Objects/Effects/Revenant Tracer.lua")
dofile("doomData/Definitions/Inventory/Ammo.lua")
dofile("doomData/Definitions/Inventory/Weps.lua")
dofile("doomData/Definitions/Objects/Deco.lua")
dofile("doomData/Definitions/Objects/Artifacts/Invuln.lua")
dofile("doomData/Definitions/Objects/Artifacts/Berserk.lua")
dofile("doomData/Definitions/Objects/Artifacts/Megasphere.lua")
dofile("doomData/Definitions/Objects/Artifacts/Blursphere.lua")
dofile("doomData/Definitions/Objects/Artifacts/Radiation Suit.lua")
dofile("doomData/Definitions/Objects/Artifacts/Soulsphere.lua")
dofile("doomData/Definitions/Objects/Artifacts/Backpack.lua")
dofile("doomData/Definitions/Objects/Artifacts/ComputerAreaMap.lua")
dofile("doomData/Definitions/Objects/Artifacts/Lite-Amp.lua")
dofile("doomData/Definitions/Objects/Items/Ammo.lua")
dofile("doomData/Definitions/Objects/Items/Armor.lua")
dofile("doomData/Definitions/Objects/Items/Health.lua")
dofile("doomData/Definitions/Objects/Items/Weapons.lua")
dofile("doomData/Definitions/Objects/Keycards/Yellow Key.lua")
dofile("doomData/Definitions/Objects/Keycards/Blue Key.lua")
dofile("doomData/Definitions/Objects/Keycards/Red Key.lua")
dofile("doomData/Definitions/Objects/Keycards/Yellow Skull Key.lua")
dofile("doomData/Definitions/Objects/Keycards/Blue Skull Key.lua")
dofile("doomData/Definitions/Objects/Keycards/Red Skull Key.lua")
dofile("doomData/Definitions/Objects/Monsters/Commander Keen.lua")
dofile("doomData/Definitions/Objects/Monsters/Cacodemon.lua")
dofile("doomData/Definitions/Objects/Monsters/Cyberdemon.lua")
dofile("doomData/Definitions/Objects/Monsters/Spider Mastermind.lua")
dofile("doomData/Definitions/Objects/Monsters/Imp.lua")
dofile("doomData/Definitions/Objects/Monsters/Zombieman.lua")
dofile("doomData/Definitions/Objects/Monsters/Shotgunner.lua")
dofile("doomData/Definitions/Objects/Monsters/Chaingunner.lua")
dofile("doomData/Definitions/Objects/Monsters/Demon.lua")
dofile("doomData/Definitions/Objects/Monsters/SS Guard.lua")
dofile("doomData/Definitions/Objects/Monsters/Hell Knight.lua")
dofile("doomData/Definitions/Objects/Monsters/RomeroHead.lua")
dofile("doomData/Definitions/Objects/Monsters/Exploding Barrel.lua")
dofile("doomData/Definitions/Objects/Monsters/Mancubus.lua")
dofile("doomData/Definitions/Objects/Monsters/Arachnotron.lua")
dofile("doomData/Definitions/Objects/Monsters/Revenant.lua")
dofile("doomData/Definitions/Objects/Monsters/Lost Soul.lua")
dofile("doomData/Definitions/Objects/Monsters/Pain Elemental.lua")
dofile("doomData/Definitions/Objects/Monsters/Voodoo Doll.lua")
dofile("doomData/Definitions/Objects/Monsters/PLACEHOLD/Archvile.lua")
dofile("doomData/Definitions/Objects/MiscDeco.lua")

dofile("doomData/HUD/Cast Drawer.lua")
dofile("doomData/HUD/HUD.lua")